import { createSupabaseServerClient } from '@/lib/supabase/server';
import { requireCurrentUser } from '@/lib/session';
import { marketingOAuthReadiness,marketingOAuthMissingSettings } from '@/lib/integrations/marketing-oauth';

export const dynamic='force-dynamic';
const label=(p:string)=>p==='google_ads'?'Google Ads':'Facebook / Instagram';
const pretty=(s:string)=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());

export default async function MarketingProvidersPage({searchParams}:{searchParams:Promise<{provider?:string,status?:string}>}){
 const params=await searchParams;
 const notices:Record<string,string>={
   configuration_required:'Connection setup is incomplete. The missing settings are listed below.',
   denied:'Authorization was cancelled or declined. No connection was saved.',
   forbidden:'Only the owner can authorize an ad account.',
   authorization_response_error:'The sign-in response expired or could not be verified. Start authorization again.',
   token_exchange_error:'Google sign-in returned, but Google could not finish exchanging the authorization. The connection was not saved.',
   token_storage_error:'Google sign-in succeeded, but the app could not save the connection. The server logs contain the database error.',
   error:'The connection could not be completed. The server logs contain the error.',
 };
 const notice=params.status?notices[params.status]:undefined;
 const user=await requireCurrentUser();const supabase=await createSupabaseServerClient();const [{data:connections,error:connectionError},{data:queue}]=await Promise.all([supabase.rpc('marketing_provider_connection_summary'),supabase.rpc('marketing_sync_queue_summary')]);const rows:any[]=(connections as any[])??[],q:any[]=(queue as any[])??[];const ready=marketingOAuthReadiness();
 const providerReady:{[key:string]:boolean}={google_ads:ready.secret&&ready.database&&ready.googleClient,meta_ads:ready.secret&&ready.database&&ready.metaClient&&Boolean(process.env.META_GRAPH_VERSION?.trim())};
 return <main style={{fontFamily:'system-ui',maxWidth:1100,margin:'auto',padding:32}}><header><p style={{fontWeight:800,letterSpacing:1}}>AD PLATFORM CONNECTIONS</p><h1>Provider Authorization</h1><p>This is the secure handoff point. OAuth tokens are encrypted before storage, provider queues stay blocked until authorization/account selection succeeds, and no Google or Meta password is stored by Durfee Performance.</p></header>
 {notice&&<p role="alert" style={{padding:16,border:'1px solid #b45309',borderRadius:10}}>{notice}</p>}
 {connectionError&&<p role="alert">The saved connection status could not be loaded. Please refresh before trying to authorize again.</p>}
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:18,marginTop:24}}>{['google_ads','meta_ads'].map(provider=>{const r=rows.find(x=>x.provider===provider)||{};const pending=q.filter(x=>x.provider===provider&&['waiting_authorization','ready','failed'].includes(x.status)).reduce((s,x)=>s+Number(x.event_count||0),0);const start=provider==='google_ads'?'/api/integrations/google-ads/oauth/start':'/api/integrations/meta-ads/oauth/start';return <article key={provider} style={{border:'1px solid #ddd',borderRadius:16,padding:20}}><h2 style={{marginTop:0}}>{label(provider)}</h2><p><b>Status:</b> {connectionError?'Unavailable':pretty(r.connection_status||'authorization_required')}</p><p><b>OAuth configuration:</b> {providerReady[provider]?'Ready':'Setup required'}</p><p><b>Conversions staged:</b> {pending.toLocaleString()}</p>{r.account_name&&<p><b>Account:</b> {r.account_name}</p>}{r.last_synced_at&&<p><b>Last sync:</b> {new Date(r.last_synced_at).toLocaleString()}</p>}{r.last_error&&<p role="alert"><b>Last error:</b> {r.last_error}</p>}{user.role==='owner'&&providerReady[provider]?<a href={start} style={{display:'inline-block',padding:'10px 14px',border:'1px solid #111',borderRadius:10,textDecoration:'none',fontWeight:700}}>{r.connection_status==='authorized'?'Reauthorize':'Authorize'} {label(provider)}</a>:user.role==='owner'?<div role="alert"><p>Missing production settings:</p><ul>{marketingOAuthMissingSettings(provider as 'google_ads'|'meta_ads').map(name=><li key={name}><code>{name}</code></li>)}</ul><p><small>Add these in <a href="https://vercel.com/durfee-performance-ai/durfee-performance-ai/settings/environment-variables" target="_blank" rel="noopener noreferrer">Vercel environment settings</a>, then redeploy. Enter secret values only in Vercel.</small></p></div>:<p><small>Only the owner can authorize an ad account.</small></p>}</article>;})}</section>
 <section style={{border:'1px solid #ddd',borderRadius:16,padding:20,marginTop:24}}><h2 style={{marginTop:0}}>Server credential readiness</h2><p><b>Supabase server credential:</b> {ready.database?'Ready':'Missing — set SUPABASE_SECRET_KEY in Production and redeploy'}</p><p><b>Shared OAuth encryption/state secret:</b> {ready.secret?'Ready':'Missing or shorter than 32 characters'}</p><p><b>Google OAuth client:</b> {ready.googleClient?'Ready':'Missing'}</p><p><b>Google Ads API access:</b> Check your <a href="https://console.cloud.google.com/google/ads-apis/overview?project=durfee-performance-ai" target="_blank" rel="noopener noreferrer">Google Cloud project access level</a>. Live account data requires Explorer access or higher in the project that owns your OAuth client. Authorization alone does not confirm this approval.</p><p><b>Meta app credentials:</b> {ready.metaClient?'Ready':'Missing'} • <b>Meta Graph API version:</b> {process.env.META_GRAPH_VERSION?.trim()?'Ready':'Missing'}</p><p><small>Secrets belong in the production environment settings, not in chat. Google redirects back to <code>/api/integrations/google-ads/oauth/callback</code>; Meta redirects back to <code>/api/integrations/meta-ads/oauth/callback</code>.</small></p></section>
 <section style={{border:'1px solid #ddd',borderRadius:16,padding:20,marginTop:24}}><h2 style={{marginTop:0}}>What happens after consent</h2><p>Google requests Data Manager + Google Ads access. Meta requests ads read/management + business access. The callback exchanges the authorization code server-side, encrypts the resulting token, records the granted scopes, and returns here. We then verify/select the actual Durfee ad account before enabling recurring spend imports or conversion uploads.</p></section>
 </main>;
}
