import Link from 'next/link';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { requireCurrentUser } from '@/lib/session';
import { marketingOAuthReadiness } from '@/lib/integrations/marketing-oauth';

export const dynamic='force-dynamic';
const label=(p:string)=>p==='google_ads'?'Google Ads':'Facebook / Instagram';
const pretty=(s:string)=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());

export default async function MarketingProvidersPage(){
 const user=await requireCurrentUser();const supabase=await createSupabaseServerClient();const [{data:connections},{data:queue}]=await Promise.all([supabase.rpc('marketing_provider_connection_summary'),supabase.rpc('marketing_sync_queue_summary')]);const rows:any[]=(connections as any[])??[],q:any[]=(queue as any[])??[];const ready=marketingOAuthReadiness();
 const providerReady:{[key:string]:boolean}={google_ads:ready.secret&&ready.googleClient&&ready.googleDeveloperToken,meta_ads:ready.secret&&ready.metaClient&&Boolean(process.env.META_GRAPH_VERSION?.trim())};
 return <main style={{fontFamily:'system-ui',maxWidth:1100,margin:'auto',padding:32}}><header><p style={{fontWeight:800,letterSpacing:1}}>AD PLATFORM CONNECTIONS</p><h1>Provider Authorization</h1><p>This is the secure handoff point. OAuth tokens are encrypted before storage, provider queues stay blocked until authorization/account selection succeeds, and no Google or Meta password is stored by Durfee Performance.</p></header>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:18,marginTop:24}}>{['google_ads','meta_ads'].map(provider=>{const r=rows.find(x=>x.provider===provider)||{};const pending=q.filter(x=>x.provider===provider&&['waiting_authorization','ready','failed'].includes(x.status)).reduce((s,x)=>s+Number(x.event_count||0),0);const start=provider==='google_ads'?'/api/integrations/google-ads/oauth/start':'/api/integrations/meta-ads/oauth/start';return <article key={provider} style={{border:'1px solid #ddd',borderRadius:16,padding:20}}><h2 style={{marginTop:0}}>{label(provider)}</h2><p><b>Status:</b> {pretty(r.connection_status||'authorization_required')}</p><p><b>OAuth configuration:</b> {providerReady[provider]?'Ready':'Setup required'}</p><p><b>Conversions staged:</b> {pending.toLocaleString()}</p>{r.account_name&&<p><b>Account:</b> {r.account_name}</p>}{r.last_synced_at&&<p><b>Last sync:</b> {new Date(r.last_synced_at).toLocaleString()}</p>}{r.last_error&&<p role="alert"><b>Last error:</b> {r.last_error}</p>}{user.role==='owner'&&providerReady[provider]?<Link href={start} style={{display:'inline-block',padding:'10px 14px',border:'1px solid #111',borderRadius:10,textDecoration:'none',fontWeight:700}}>{r.connection_status==='authorized'?'Reauthorize':'Authorize'} {label(provider)}</Link>:<p><small>Owner authorization becomes available when the required server credentials are present.</small></p>}</article>;})}</section>
 <section style={{border:'1px solid #ddd',borderRadius:16,padding:20,marginTop:24}}><h2 style={{marginTop:0}}>Server credential readiness</h2><p><b>Shared OAuth encryption/state secret:</b> {ready.secret?'Ready':'Missing'}</p><p><b>Google OAuth client:</b> {ready.googleClient?'Ready':'Missing'} • <b>Google Ads developer token:</b> {ready.googleDeveloperToken?'Ready':'Missing'}</p><p><b>Meta app credentials:</b> {ready.metaClient?'Ready':'Missing'} • <b>Meta Graph API version:</b> {process.env.META_GRAPH_VERSION?.trim()?'Ready':'Missing'}</p><p><small>Secrets belong in the production environment settings, not in chat. Google redirects back to <code>/api/integrations/google-ads/oauth/callback</code>; Meta redirects back to <code>/api/integrations/meta-ads/oauth/callback</code>.</small></p></section>
 <section style={{border:'1px solid #ddd',borderRadius:16,padding:20,marginTop:24}}><h2 style={{marginTop:0}}>What happens after consent</h2><p>Google requests Data Manager + Google Ads access. Meta requests ads read/management + business access. The callback exchanges the authorization code server-side, encrypts the resulting token, records the granted scopes, and returns here. We then verify/select the actual Durfee ad account before enabling recurring spend imports or conversion uploads.</p></section>
 </main>;
}
