'use server';
import {revalidatePath} from 'next/cache';import {createSupabaseServerClient} from '@/lib/supabase/server';import {assertPermission} from '@/lib/permissions';
async function finance(){await assertPermission('manage_accounting');return {s:await createSupabaseServerClient()};}
function refreshAccounting(jobId?:string){for(const p of ['/accounting/vendor-bills','/billing','/dashboard','/reports/daily','/reports/profitability'])revalidatePath(p);if(jobId)revalidatePath(`/jobs/${jobId}`);}
export async function approveVendorBill(formData:FormData){const {s}=await finance();const id=String(formData.get('bill_id')??''),invoiceNumber=String(formData.get('invoice_number')??'').trim(),invoiceDate=String(formData.get('invoice_date')??''),dueDate=String(formData.get('due_date')??''),subtotal=Number(formData.get('subtotal')??0),tax=Number(formData.get('tax')??0),total=Number(formData.get('total')??0),accountCode=String(formData.get('account_code')??'materials_cogs').trim(),memo=String(formData.get('memo')??'').trim().slice(0,2000);if(!id)throw new Error('Bill is required');if(!invoiceNumber)throw new Error('Vendor invoice number is required before posting');if(!Number.isFinite(subtotal)||subtotal<0||!Number.isFinite(tax)||tax<0||!Number.isFinite(total)||total<=0)throw new Error('Enter valid non-negative subtotal/tax and a positive total');if(Math.abs((subtotal+tax)-total)>0.02)throw new Error('Invoice total must equal subtotal plus tax before posting');if(invoiceDate&&dueDate&&dueDate<invoiceDate)throw new Error('Due date cannot be before invoice date');const {error}=await s.rpc('review_and_approve_vendor_bill',{p_bill_id:id,p_invoice_number:invoiceNumber,p_invoice_date:invoiceDate||null,p_due_date:dueDate||null,p_subtotal:subtotal,p_tax:tax,p_total:total,p_account_code:accountCode||'materials_cogs',p_memo:memo||null});if(error)throw new Error(error.message||'Vendor bill could not be approved');refreshAccounting();}
export async function rejectVendorBill(formData:FormData){const {s}=await finance();const id=String(formData.get('bill_id')??''),reason=String(formData.get('reason')??'').trim();if(!id||reason.length<3||reason.length>1000)throw new Error('Enter a valid rejection reason');const {error}=await s.rpc('reject_vendor_bill_atomic',{p_bill_id:id,p_reason:reason});if(error)throw new Error(error.message||'Bill could not be rejected');revalidatePath('/purchasing');refreshAccounting();}
export async function recordApPayment(formData:FormData){const {s}=await finance();const id=String(formData.get('ap_id')??''),amount=Number(formData.get('amount')??0),paidAt=String(formData.get('paid_at')??''),method=String(formData.get('payment_method')??'').trim().slice(0,80),reference=String(formData.get('reference')??'').trim().slice(0,160),notes=String(formData.get('notes')??'').trim().slice(0,1000);if(!id||!Number.isFinite(amount)||amount<=0||!method)throw new Error('Enter a valid payment amount and method');const {error}=await s.rpc('record_ap_payment',{p_ap_id:id,p_amount:amount,p_paid_at:paidAt?`${paidAt}T12:00:00.000Z`:new Date().toISOString(),p_payment_method:method,p_reference:reference||null,p_notes:notes||null});if(error)throw new Error(error.message||'Payment could not be recorded');refreshAccounting();}
export async function allocateApToJob(formData:FormData){const {s}=await finance();const apId=String(formData.get('ap_id')??''),jobId=String(formData.get('job_id')??''),amount=Number(formData.get('amount')??0),type=String(formData.get('allocation_type')??'materials'),notes=String(formData.get('notes')??'').trim().slice(0,1000);if(!apId||!jobId||!Number.isFinite(amount)||amount<=0)throw new Error('Choose a job and enter a valid allocation');if(!['materials','subcontractor','equipment','permit','other'].includes(type))throw new Error('Invalid allocation type');const {error}=await s.rpc('allocate_ap_to_job',{p_ap_id:apId,p_job_id:jobId,p_amount:amount,p_type:type,p_notes:notes||null});if(error)throw new Error(error.message||'Job cost allocation could not be recorded');refreshAccounting(jobId);}
export async function reverseApPayment(formData:FormData){const {s}=await finance();const id=String(formData.get('payment_id')??''),reason=String(formData.get('reason')??'').trim();if(!id||reason.length<3||reason.length>1000)throw new Error('Enter a valid payment reversal reason');const {error}=await s.rpc('reverse_ap_payment_atomic',{p_payment_id:id,p_reason:reason});if(error)throw new Error(error.message||'Payment could not be reversed');refreshAccounting();}
export async function reverseJobAllocation(formData:FormData){const {s}=await finance();const id=String(formData.get('allocation_id')??''),jobId=String(formData.get('job_id')??''),reason=String(formData.get('reason')??'').trim();if(!id||reason.length<3||reason.length>1000)throw new Error('Enter a valid allocation reversal reason');const {error}=await s.rpc('reverse_job_cost_allocation_atomic',{p_allocation_id:id,p_reason:reason});if(error)throw new Error(error.message||'Allocation could not be reversed');refreshAccounting(jobId||undefined);}
export async function voidApEntry(formData:FormData){const {s}=await finance();const id=String(formData.get('ap_id')??''),reason=String(formData.get('reason')??'').trim();if(!id||reason.length<3||reason.length>1000)throw new Error('Enter a valid AP void reason');const {error}=await s.rpc('void_ap_entry_atomic',{p_ap_id:id,p_reason:reason});if(error)throw new Error(error.message||'AP bill could not be voided');refreshAccounting();}
