import Link from 'next/link';
import {createSupabaseServerClient} from '@/lib/supabase/server';
import {requireCurrentUser} from '@/lib/session';

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const one=(v:any)=>Array.isArray(v)?v[0]:v;
function extraCost(j:any){return (j.job_cost_allocations??[]).filter((a:any)=>!a.reversed_at&&a.allocation_type!=='materials').reduce((s:number,a:any)=>s+Number(a.amount??0),0)}
function actualCost(j:any){return Number(j.material_cost??0)+Number(j.labor_cost??0)+Number(j.allocated_overhead??0)+extraCost(j)}
function allowedDays(v?:string){const n=Number(v??90);return [30,90,365].includes(n)?n:90}
function summarize(rows:any[],key:(r:any)=>string,floor:number){const groups=new Map<string,any[]>();for(const r of rows){const k=key(r)||'Unassigned';groups.set(k,[...(groups.get(k)??[]),r])}return [...groups.entries()].map(([name,jobs])=>{const revenue=jobs.reduce((s,j)=>s+j.revenue,0),cost=jobs.reduce((s,j)=>s+j.cost,0),gross=revenue-cost,gp=revenue>0?gross/revenue*100:0,below=jobs.filter(j=>j.gp<floor),hitRate=jobs.length?((jobs.length-below.length)/jobs.length)*100:0,shortfall=below.reduce((s,j)=>s+Math.max(0,j.revenue*(floor/100)-j.gross),0);return {name,jobs:jobs.length,revenue,cost,gross,gp,below:below.length,hitRate,shortfall}}).sort((a,b)=>a.gp-b.gp)}

export default async function ProfitabilityPage({searchParams}:{searchParams:Promise<{days?:string}>}){
  const user=await requireCurrentUser();
  if(!['owner','manager','accounting'].includes(user.role))return <main style={{padding:32}}><h1>Job Profitability</h1><p>No access.</p></main>;
  const sp=await searchParams,days=allowedDays(sp.days),since=new Date(Date.now()-days*86400000),s=await createSupabaseServerClient();
  const [{data:jobs},{data:settings}]=await Promise.all([
    s.from('jobs').select('id,status,service_type,service_summary,scheduled_start,completed_at,revenue,material_cost,labor_hours,labor_cost,allocated_overhead,customers(name,customer_code),users!jobs_technician_id_fkey(name),job_cost_allocations(amount,allocation_type,reversed_at)').gte('completed_at',since.toISOString()).order('completed_at',{ascending:false}).limit(1000),
    s.from('company_pricing_settings').select('minimum_gp').limit(1).maybeSingle()
  ]);
  const floor=Number(settings?.minimum_gp??50),rows=(jobs??[]).map((j:any)=>{const revenue=Number(j.revenue??0),material=Number(j.material_cost??0),labor=Number(j.labor_cost??0),overhead=Number(j.allocated_overhead??0),extra=extraCost(j),cost=actualCost(j),gross=revenue-cost,gp=revenue>0?gross/revenue*100:0;return {...j,revenue,material,labor,overhead,extra,cost,gross,gp}}),billed=rows.filter(r=>r.revenue>0),totalRevenue=billed.reduce((a,r)=>a+r.revenue,0),totalCost=billed.reduce((a,r)=>a+r.cost,0),portfolioGp=totalRevenue?((totalRevenue-totalCost)/totalRevenue*100):0,below=billed.filter(r=>r.gp<floor),warning=billed.filter(r=>r.gp>=floor&&r.gp<floor+5),shortfall=below.reduce((s,j)=>s+Math.max(0,j.revenue*(floor/100)-j.gross),0),techSummary=summarize(billed,j=>one(j.users)?.name||'Unassigned',floor),serviceSummary=summarize(billed,j=>j.service_type||'Unclassified',floor);
  return <main style={{fontFamily:'system-ui',maxWidth:1350,margin:'auto',padding:32}}>
    <div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h1>Job Profitability / GP Control Center</h1><p>Completed billed jobs for the last <b>{days} days</b>. Actual cost includes labor, materials, overhead and active non-material vendor-bill allocations. Company GP floor: <b>{floor.toFixed(1)}%</b>.</p></div><div><Link href="/reports/daily">Daily report →</Link> · <Link href="/jobs/gp-approvals">Low-GP approvals →</Link></div></div>
    <nav style={{display:'flex',gap:8,margin:'14px 0'}}>{[30,90,365].map(d=><Link key={d} href={`/reports/profitability?days=${d}`} style={{padding:'7px 10px',border:'1px solid #ccc',borderRadius:9,textDecoration:'none',fontWeight:d===days?800:400}}>{d} days</Link>)}</nav>
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12,margin:'22px 0'}}>{[['Revenue',money.format(totalRevenue)],['Actual Cost',money.format(totalCost)],['Portfolio GP',`${portfolioGp.toFixed(1)}%`],['Completed Billed Jobs',String(billed.length)],['Below Floor',String(below.length)],['Watch List',String(warning.length)],['GP Dollar Shortfall',money.format(shortfall)]].map(([a,b])=><article key={a} style={{border:'1px solid #ddd',borderRadius:14,padding:16}}><small>{a}</small><h2>{b}</h2></article>)}</section>

    <h2>Technician Profitability Scorecard</h2><p><small>Target-hit rate is the share of completed billed jobs meeting the company GP floor. This is an operating metric, not an automatic personnel decision.</small></p>
    <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Technician','Jobs','Revenue','Actual Cost','GP','Target Hit Rate','Below Floor','GP Shortfall'].map(h=><th key={h} style={{textAlign:'left',padding:9,borderBottom:'1px solid #bbb'}}>{h}</th>)}</tr></thead><tbody>{techSummary.map(r=><tr key={r.name} style={{background:r.gp<floor?'#fff8f6':undefined}}><td style={{padding:9}}><b>{r.name}</b></td><td>{r.jobs}</td><td>{money.format(r.revenue)}</td><td>{money.format(r.cost)}</td><td><b>{r.gp.toFixed(1)}%</b></td><td>{r.hitRate.toFixed(0)}%</td><td>{r.below}</td><td>{money.format(r.shortfall)}</td></tr>)}</tbody></table></div>

    <h2 style={{marginTop:32}}>Service-Type Profitability</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Service Type','Jobs','Revenue','Actual Cost','GP','Target Hit Rate','Below Floor','GP Shortfall'].map(h=><th key={h} style={{textAlign:'left',padding:9,borderBottom:'1px solid #bbb'}}>{h}</th>)}</tr></thead><tbody>{serviceSummary.map(r=><tr key={r.name} style={{background:r.gp<floor?'#fff8f6':undefined}}><td style={{padding:9}}><b>{r.name}</b></td><td>{r.jobs}</td><td>{money.format(r.revenue)}</td><td>{money.format(r.cost)}</td><td><b>{r.gp.toFixed(1)}%</b></td><td>{r.hitRate.toFixed(0)}%</td><td>{r.below}</td><td>{money.format(r.shortfall)}</td></tr>)}</tbody></table></div>

    <h2 style={{marginTop:32}}>Jobs Requiring Attention</h2>{[...below,...warning].sort((a,b)=>a.gp-b.gp).map((j:any)=><article key={j.id} style={{border:j.gp<floor?'2px solid currentColor':'1px solid #aaa',borderRadius:14,padding:16,margin:'10px 0'}}><div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><h3 style={{margin:'0 0 5px'}}>{one(j.customers)?.customer_code||''} {one(j.customers)?.name||'Customer'} • {j.service_type||'Service'}</h3><small>{one(j.users)?.name||'Unassigned'} • completed {j.completed_at?new Date(j.completed_at).toLocaleDateString('en-US',{timeZone:'America/New_York'}):'—'} • <Link href={`/jobs/${j.id}`}>Open job</Link></small></div><div style={{textAlign:'right'}}><b style={{fontSize:24}}>{j.gp.toFixed(1)}% GP</b><br/><small>{j.gp<floor?'BELOW FLOOR':'WATCH'}</small></div></div><p>Revenue <b>{money.format(j.revenue)}</b> − Materials {money.format(j.material)} − Labor {money.format(j.labor)} − Overhead {money.format(j.overhead)}{j.extra>0?` − Other vendor costs ${money.format(j.extra)}`:''} = <b>{money.format(j.gross)} gross profit</b></p>{j.gp<floor&&<p><b>GP dollar shortfall:</b> {money.format(Math.max(0,j.revenue*(floor/100)-j.gross))} below the company target.</p>}</article>)}{!below.length&&!warning.length&&<p>No completed billed jobs are currently inside the GP alert range.</p>}

    <h2 style={{marginTop:30}}>All Completed Billed Jobs</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Customer','Technician','Service','Revenue','Material','Labor','Overhead','Other Vendor','Gross Profit','GP'].map(h=><th key={h} style={{textAlign:'left',padding:8,borderBottom:'1px solid #bbb'}}>{h}</th>)}</tr></thead><tbody>{billed.map((j:any)=><tr key={j.id}><td style={{padding:8}}><Link href={`/jobs/${j.id}`}>{one(j.customers)?.customer_code} {one(j.customers)?.name}</Link></td><td>{one(j.users)?.name||'Unassigned'}</td><td>{j.service_type||'—'}</td><td>{money.format(j.revenue)}</td><td>{money.format(j.material)}</td><td>{money.format(j.labor)}</td><td>{money.format(j.overhead)}</td><td>{j.extra?money.format(j.extra):'—'}</td><td>{money.format(j.gross)}</td><td><b>{j.gp.toFixed(1)}%</b></td></tr>)}</tbody></table></div>
    <aside style={{marginTop:28,border:'1px solid #ddd',borderRadius:14,padding:16}}><h2>How to use this</h2><p>If one technician is weak across many service types, review field time, material control and close rates. If many technicians miss target on the same service type, review the price book, expected labor and material assumptions before blaming execution. GP shortfall shows the gross-profit dollars needed for below-floor jobs to have reached the configured target.</p></aside>
  </main>
}
