'use server';
import { revalidatePath } from 'next/cache';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { requireCurrentUser } from '@/lib/session';
import { assertPermission,hasPermission } from '@/lib/permissions';

async function fieldUser(){await assertPermission('field_app');return requireCurrentUser();}
async function context(jobId:string){const user=await fieldUser();const supabase=await createSupabaseServerClient();const {data:job,error}=await supabase.from('jobs').select('id,technician_id,status').eq('id',jobId).single();if(error||!job)throw new Error('Job not found');const canManage=(await hasPermission('manage_jobs'))||(await hasPermission('manage_dispatch'));if(job.technician_id!==user.id&&!canManage)throw new Error('Field users can only update their assigned jobs');return {user,supabase,job};}
async function fieldClient(){await fieldUser();return createSupabaseServerClient();}
function refreshCloseout(jobId:string){for(const p of ['/field','/jobs',`/jobs/${jobId}`,'/schedule','/dispatch','/dashboard','/jobs/zero-invoice-approvals','/jobs/gp-approvals'])revalidatePath(p);}

export async function setFieldStatus(formData:FormData){const jobId=String(formData.get('job_id')??''),status=String(formData.get('status')??'');if(!jobId)throw new Error('Job required');if(!['en_route','on_site','work_complete'].includes(status))throw new Error('Invalid status');const supabase=await fieldClient();const {error}=await supabase.rpc('set_field_status_atomic',{p_job_id:jobId,p_requested_status:status,p_no_materials:String(formData.get('no_materials')??'')==='on'});if(error)throw new Error(error.message||'Job status could not be updated');refreshCloseout(jobId);}
export async function requestZeroInvoiceApproval(formData:FormData){const jobId=String(formData.get('job_id')??'');if(!jobId)throw new Error('Job required');const supabase=await fieldClient();const {error}=await supabase.rpc('request_zero_invoice_closeout_approval',{p_job_id:jobId});if(error)throw new Error(error.message||'Manager approval request could not be created');refreshCloseout(jobId);}
export async function requestGpCloseoutApproval(formData:FormData){const jobId=String(formData.get('job_id')??'');if(!jobId)throw new Error('Job required');const supabase=await fieldClient();const {error}=await supabase.rpc('request_gp_closeout_approval',{p_job_id:jobId});if(error)throw new Error(error.message||'Low-GP approval request could not be created');refreshCloseout(jobId);}
export async function addTimeEntry(formData:FormData){const jobId=String(formData.get('job_id')??''),hours=Number(formData.get('hours')??0);if(!jobId)throw new Error('Job required');if(!(hours>0&&hours<=24))throw new Error('Enter valid hours');const supabase=await fieldClient();const {error}=await supabase.rpc('add_work_time_atomic',{p_job_id:jobId,p_hours:hours});if(error)throw new Error(error.message||'Time could not be saved');revalidatePath('/field');revalidatePath(`/jobs/${jobId}`);}
export async function useInventoryMaterial(formData:FormData){const jobId=String(formData.get('job_id')??''),itemId=String(formData.get('inventory_item_id')??''),quantity=Number(formData.get('quantity')??0);if(!jobId||!itemId||quantity<=0)throw new Error('Choose material and quantity');const {supabase,job}=await context(jobId);if(job.status!=='on_site')throw new Error('Mark the job On Site before recording materials');const {error}=await supabase.rpc('consume_inventory_for_job',{p_job_id:jobId,p_inventory_item_id:itemId,p_quantity:quantity});if(error)throw new Error(error.message||'Inventory material could not be recorded');revalidatePath('/field');revalidatePath('/inventory');revalidatePath(`/jobs/${jobId}`);}
export async function addMaterial(formData:FormData){const jobId=String(formData.get('job_id')??''),quantity=Number(formData.get('quantity')??0),unitCost=Number(formData.get('unit_cost')??0);if(!jobId)throw new Error('Job required');if(!(quantity>0))throw new Error('Quantity must be positive');if(!Number.isFinite(unitCost)||unitCost<0)throw new Error('Unit cost cannot be negative');const supabase=await fieldClient();const {error}=await supabase.rpc('add_field_material_atomic',{p_job_id:jobId,p_sku:String(formData.get('sku')??'FIELD').trim()||'FIELD',p_description:String(formData.get('description')??'').trim()||'Field material',p_quantity:quantity,p_unit_cost:unitCost});if(error)throw new Error(error.message||'Material could not be saved');revalidatePath('/field');revalidatePath(`/jobs/${jobId}`);}
export async function addJobNote(formData:FormData){const jobId=String(formData.get('job_id')??''),note=String(formData.get('note')??'').trim(),noteType=String(formData.get('note_type')??'work');if(!jobId)throw new Error('Job required');if(!note||note.length>5000)throw new Error('Enter a valid note');if(!['work','diagnostic','customer','internal','completion'].includes(noteType))throw new Error('Invalid note type');const supabase=await fieldClient();const {error}=await supabase.rpc('add_job_note_atomic',{p_job_id:jobId,p_note_type:noteType,p_note:note});if(error)throw new Error(error.message||'Job note could not be saved');revalidatePath('/field');revalidatePath('/jobs');revalidatePath(`/jobs/${jobId}`);}
export async function uploadJobPhoto(formData:FormData){const jobId=String(formData.get('job_id')??''),caption=String(formData.get('caption')??'').trim().slice(0,500),file=formData.get('photo');if(!jobId)throw new Error('Job required');if(!(file instanceof File)||file.size===0)throw new Error('Choose a photo');if(file.size>10*1024*1024)throw new Error('Photo must be 10 MB or smaller');const allowed=new Set(['image/jpeg','image/png','image/webp','image/heic','image/heif']);if(!allowed.has(file.type))throw new Error('Use a JPEG, PNG, WebP, HEIC or HEIF image');const {supabase}=await context(jobId),ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase()||'jpg',path=`${jobId}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await supabase.storage.from('job-photos').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw new Error('Photo upload failed');const {error:finalizeError}=await supabase.rpc('finalize_job_photo_atomic',{p_job_id:jobId,p_storage_path:path,p_caption:caption||null});if(finalizeError){const {error:cleanupError}=await supabase.storage.from('job-photos').remove([path]);if(cleanupError)throw new Error('Photo metadata failed and storage cleanup also failed; contact a manager');throw new Error(finalizeError.message||'Photo record could not be saved');}revalidatePath('/field');revalidatePath('/jobs');revalidatePath(`/jobs/${jobId}`);}
