-- Canonicalize accounts_payable_entries and retire duplicate AP write paths.
alter table public.accounts_payable_entries add column if not exists balance_due numeric;
alter table public.accounts_payable_entries add column if not exists account_code text;
alter table public.accounts_payable_entries add column if not exists memo text;
alter table public.accounts_payable_entries drop constraint if exists accounts_payable_entries_status_check;
alter table public.accounts_payable_entries add constraint accounts_payable_entries_status_check check(status in ('open','partial','paid','void'));
update public.accounts_payable_entries set balance_due=coalesce(balance_due,total) where balance_due is null;
alter table public.accounts_payable_entries alter column balance_due set default 0;

-- Bring any rows written to the duplicate table into the canonical ledger.
insert into public.accounts_payable_entries(vendor_bill_id,supplier_id,customer_id,invoice_number,invoice_date,due_date,total,balance_due,status,account_code,memo,posted_by,posted_at,created_at)
select vendor_bill_id,supplier_id,customer_id,invoice_number,invoice_date,due_date,total,balance_due,status,account_code,memo,posted_by,posted_at,created_at from public.accounts_payable
on conflict(vendor_bill_id) do update set balance_due=excluded.balance_due,status=excluded.status,account_code=coalesce(excluded.account_code,public.accounts_payable_entries.account_code),memo=coalesce(excluded.memo,public.accounts_payable_entries.memo);

-- Repoint dependent records before removing the duplicate table.
alter table public.ap_payments add column if not exists accounts_payable_entry_id uuid references public.accounts_payable_entries(id) on delete restrict;
update public.ap_payments p set accounts_payable_entry_id=e.id from public.accounts_payable a join public.accounts_payable_entries e on e.vendor_bill_id=a.vendor_bill_id where p.accounts_payable_id=a.id and p.accounts_payable_entry_id is null;
alter table public.job_cost_allocations add column if not exists accounts_payable_entry_id uuid references public.accounts_payable_entries(id) on delete restrict;
update public.job_cost_allocations c set accounts_payable_entry_id=e.id from public.accounts_payable a join public.accounts_payable_entries e on e.vendor_bill_id=a.vendor_bill_id where c.accounts_payable_id=a.id and c.accounts_payable_entry_id is null;

create or replace function public.record_ap_payment(p_ap_id uuid,p_amount numeric,p_paid_at timestamptz,p_payment_method text,p_reference text,p_notes text) returns uuid language plpgsql security definer set search_path=public as $$declare u public.users%rowtype;a public.accounts_payable_entries%rowtype;pid uuid;begin select * into u from public.users where auth_user_id=auth.uid() and active=true limit 1;if u.id is null or u.role not in ('owner','manager','accounting') then raise exception 'not authorized';end if;select * into a from public.accounts_payable_entries where id=p_ap_id for update;if a.id is null then raise exception 'AP bill not found';end if;if p_amount<=0 or p_amount>a.balance_due then raise exception 'payment exceeds balance due';end if;insert into public.ap_payments(accounts_payable_id,accounts_payable_entry_id,amount,paid_at,payment_method,reference_number,notes,recorded_by) values(null,a.id,p_amount,coalesce(p_paid_at,now()),trim(p_payment_method),nullif(trim(p_reference),''),nullif(trim(p_notes),''),u.id) returning id into pid;update public.accounts_payable_entries set balance_due=balance_due-p_amount,status=case when balance_due-p_amount=0 then 'paid' else 'partial' end where id=a.id;insert into public.audit_log(actor_user_id,action,entity_type,entity_id,after_data) values(u.id,'record_ap_payment','accounts_payable_entry',a.id,jsonb_build_object('amount',p_amount,'method',p_payment_method,'reference',p_reference));return pid;end$$;

create or replace function public.allocate_ap_to_job(p_ap_id uuid,p_job_id uuid,p_amount numeric,p_type text,p_notes text) returns uuid language plpgsql security definer set search_path=public as $$declare u public.users%rowtype;a public.accounts_payable_entries%rowtype;j public.jobs%rowtype;allocated numeric;aid uuid;begin select * into u from public.users where auth_user_id=auth.uid() and active=true limit 1;if u.id is null or u.role not in ('owner','manager','accounting') then raise exception 'not authorized';end if;select * into a from public.accounts_payable_entries where id=p_ap_id for update;if a.id is null then raise exception 'AP bill not found';end if;select * into j from public.jobs where id=p_job_id;if j.id is null then raise exception 'job not found';end if;if a.customer_id is not null and a.customer_id<>j.customer_id then raise exception 'bill customer does not match job customer';end if;if p_amount<=0 then raise exception 'allocation must be positive';end if;select coalesce(sum(amount),0) into allocated from public.job_cost_allocations where accounts_payable_entry_id=a.id;if allocated+p_amount>a.total then raise exception 'allocation exceeds bill total';end if;insert into public.job_cost_allocations(accounts_payable_id,accounts_payable_entry_id,job_id,amount,allocation_type,notes,created_by) values(null,a.id,j.id,p_amount,p_type,nullif(trim(p_notes),''),u.id) on conflict(accounts_payable_id,job_id,allocation_type) do update set amount=public.job_cost_allocations.amount+excluded.amount,notes=coalesce(excluded.notes,public.job_cost_allocations.notes) returning id into aid;-- Do not increment jobs.material_cost here. Material usage is the operational source of material cost; AP allocation is accounting traceability.
insert into public.audit_log(actor_user_id,action,entity_type,entity_id,after_data) values(u.id,'allocate_ap_job_cost','job',j.id,jsonb_build_object('accounts_payable_entry_id',a.id,'amount',p_amount,'type',p_type));return aid;end$$;

-- Vendor bill approval now initializes the canonical AP balance and accounting metadata.
create or replace function public.review_and_approve_vendor_bill(p_bill_id uuid,p_invoice_number text,p_invoice_date date,p_due_date date,p_subtotal numeric,p_tax numeric,p_total numeric,p_account_code text,p_memo text) returns uuid language plpgsql security definer set search_path=public as $$ declare v_user public.users%rowtype;v_bill public.vendor_bill_drafts%rowtype;begin select * into v_user from public.users where auth_user_id=auth.uid() and active=true limit 1;if v_user.id is null or v_user.role not in ('owner','manager','accounting') then raise exception 'not authorized';end if;if coalesce(p_total,0)<=0 then raise exception 'bill total must be positive';end if;if abs((coalesce(p_subtotal,0)+coalesce(p_tax,0))-p_total)>0.05 then raise exception 'subtotal plus tax must equal total';end if;select * into v_bill from public.vendor_bill_drafts where id=p_bill_id for update;if v_bill.id is null then raise exception 'bill not found';end if;update public.vendor_bill_drafts set invoice_number=nullif(trim(p_invoice_number),''),invoice_date=p_invoice_date,due_date=p_due_date,subtotal=p_subtotal,tax=p_tax,total=p_total,account_code=coalesce(nullif(trim(p_account_code),''),'materials_cogs'),memo=nullif(trim(p_memo),''),status='approved',approved_by=v_user.id,approved_at=now(),updated_at=now() where id=p_bill_id;insert into public.accounts_payable_entries(vendor_bill_id,purchase_order_id,supplier_id,customer_id,invoice_number,invoice_date,due_date,materials_cogs,tax,total,balance_due,status,account_code,memo,posted_by) values(p_bill_id,v_bill.purchase_order_id,v_bill.supplier_id,v_bill.customer_id,nullif(trim(p_invoice_number),''),p_invoice_date,p_due_date,p_subtotal,p_tax,p_total,p_total,'open',coalesce(nullif(trim(p_account_code),''),'materials_cogs'),nullif(trim(p_memo),''),v_user.id) on conflict(vendor_bill_id) do update set invoice_number=excluded.invoice_number,invoice_date=excluded.invoice_date,due_date=excluded.due_date,materials_cogs=excluded.materials_cogs,tax=excluded.tax,total=excluded.total,balance_due=case when public.accounts_payable_entries.status='paid' then 0 else excluded.total end,account_code=excluded.account_code,memo=excluded.memo,posted_by=excluded.posted_by,posted_at=now();update public.purchase_order_documents set analysis_status='reviewed' where id=v_bill.document_id;insert into public.audit_log(actor_user_id,action,entity_type,entity_id,after_data) values(v_user.id,'approve_vendor_bill','vendor_bill',p_bill_id,jsonb_build_object('total',p_total,'invoice_number',p_invoice_number,'account_code',p_account_code));return p_bill_id;end$$;
