create or replace function public.review_and_approve_vendor_bill(p_bill_id uuid,p_invoice_number text,p_invoice_date date,p_due_date date,p_subtotal numeric,p_tax numeric,p_total numeric,p_account_code text,p_memo text)
returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_user public.users%rowtype;v_bill public.vendor_bill_drafts%rowtype;v_ap_id uuid;v_invoice text;v_account text;begin
select * into v_user from public.users where auth_user_id=auth.uid() and active=true limit 1;if v_user.id is null or v_user.role not in ('owner','manager','accounting') then raise exception 'Not authorized';end if;
v_invoice:=btrim(coalesce(p_invoice_number,''));if v_invoice='' or length(v_invoice)>160 then raise exception 'Valid vendor invoice number required';end if;
if p_invoice_date is null then raise exception 'Invoice date is required';end if;if p_invoice_date>current_date+1 then raise exception 'Invoice date cannot be in the future';end if;if p_invoice_date<current_date-interval '3 years' then raise exception 'Invoice date is outside allowed range';end if;if p_due_date is not null and p_due_date<p_invoice_date then raise exception 'Due date cannot be before invoice date';end if;
if p_subtotal is null or p_tax is null or p_total is null or p_subtotal<0 or p_tax<0 or p_total<=0 then raise exception 'Invalid bill amounts';end if;if abs((p_subtotal+p_tax)-p_total)>0.02 then raise exception 'Subtotal plus tax must equal total';end if;
v_account:=coalesce(nullif(btrim(p_account_code),''),'materials_cogs');if length(v_account)>120 then raise exception 'Invalid account code';end if;if p_memo is not null and length(p_memo)>2000 then raise exception 'Memo is too long';end if;
select * into v_bill from public.vendor_bill_drafts where id=p_bill_id for update;if not found then raise exception 'Bill not found';end if;
if v_bill.status<>'needs_review' then raise exception 'Only bills awaiting review can be posted';end if;if v_bill.supplier_id is null then raise exception 'Supplier is required before posting';end if;
if exists(select 1 from public.accounts_payable_entries where vendor_bill_id=p_bill_id) then raise exception 'Bill has already been posted to accounts payable';end if;
if exists(select 1 from public.accounts_payable_entries ape where ape.supplier_id=v_bill.supplier_id and lower(btrim(coalesce(ape.invoice_number,'')))=lower(v_invoice) and ape.status<>'void') then raise exception 'Duplicate vendor invoice number for this supplier';end if;
update public.vendor_bill_drafts set invoice_number=v_invoice,invoice_date=p_invoice_date,due_date=p_due_date,subtotal=p_subtotal,tax=p_tax,total=p_total,account_code=v_account,memo=nullif(btrim(p_memo),''),status='posted',approved_by=v_user.id,approved_at=now(),updated_at=now() where id=p_bill_id;
insert into public.accounts_payable_entries(vendor_bill_id,purchase_order_id,supplier_id,customer_id,invoice_number,invoice_date,due_date,materials_cogs,tax,total,balance_due,status,account_code,memo,posted_by) values(p_bill_id,v_bill.purchase_order_id,v_bill.supplier_id,v_bill.customer_id,v_invoice,p_invoice_date,p_due_date,p_subtotal,p_tax,p_total,p_total,'open',v_account,nullif(btrim(p_memo),''),v_user.id) returning id into v_ap_id;
update public.purchase_order_documents set analysis_status='reviewed' where id=v_bill.document_id;
insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(v_user.id,'approve_vendor_bill','vendor_bill',p_bill_id::text,jsonb_build_object('status',v_bill.status,'invoice_number',v_bill.invoice_number,'total',v_bill.total),jsonb_build_object('status','posted','invoice_number',v_invoice,'total',p_total,'account_code',v_account,'accounts_payable_entry_id',v_ap_id));return p_bill_id;end;$$;
revoke all on function public.review_and_approve_vendor_bill(uuid,text,date,date,numeric,numeric,numeric,text,text) from public;grant execute on function public.review_and_approve_vendor_bill(uuid,text,date,date,numeric,numeric,numeric,text,text) to authenticated;