create or replace function public.record_ap_payment(p_ap_id uuid,p_amount numeric,p_paid_at timestamptz,p_payment_method text,p_reference text,p_notes text)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare u public.users%rowtype;a public.accounts_payable_entries%rowtype;pid uuid;ref text:=nullif(btrim(coalesce(p_reference,'')),'');method text:=btrim(coalesce(p_payment_method,''));paid timestamptz:=coalesce(p_paid_at,now());begin
select * into u from public.users where auth_user_id=auth.uid() and active=true limit 1;if u.id is null or u.role not in ('owner','manager','accounting') then raise exception 'Not authorized';end if;
if p_ap_id is null or p_amount is null or p_amount<=0 then raise exception 'Enter a positive payment amount';end if;if method='' or length(method)>80 then raise exception 'Enter a valid payment method';end if;if ref is not null and length(ref)>160 then raise exception 'Payment reference is too long';end if;if paid>now()+interval '1 day' or paid<now()-interval '10 years' then raise exception 'Payment date is outside the allowed range';end if;
select * into a from public.accounts_payable_entries where id=p_ap_id for update;if not found then raise exception 'AP bill not found';end if;if a.status in ('paid','void') or a.balance_due<=0 then raise exception 'AP bill is not payable';end if;if p_amount>a.balance_due then raise exception 'Payment exceeds balance due';end if;
if ref is not null and exists(select 1 from public.ap_payments x where x.accounts_payable_entry_id=a.id and lower(coalesce(x.reference_number,''))=lower(ref) and x.amount=p_amount and x.payment_method=method) then raise exception 'Possible duplicate payment: this reference, amount, and method already exist for the bill';end if;
insert into public.ap_payments(accounts_payable_id,accounts_payable_entry_id,amount,paid_at,payment_method,reference_number,notes,recorded_by) values(null,a.id,p_amount,paid,method,ref,nullif(btrim(coalesce(p_notes,'')),''),u.id) returning id into pid;
update public.accounts_payable_entries set balance_due=greatest(balance_due-p_amount,0),status=case when balance_due-p_amount<=0 then 'paid' else 'partial' end where id=a.id;
insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(u.id,'record_ap_payment','accounts_payable_entry',a.id::text,jsonb_build_object('balance_due',a.balance_due,'status',a.status),jsonb_build_object('payment_id',pid,'amount',p_amount,'method',method,'reference',ref,'paid_at',paid,'balance_due',greatest(a.balance_due-p_amount,0),'status',case when a.balance_due-p_amount<=0 then 'paid' else 'partial' end));return pid;end;$$;
revoke all on function public.record_ap_payment(uuid,numeric,timestamptz,text,text,text) from public;grant execute on function public.record_ap_payment(uuid,numeric,timestamptz,text,text,text) to authenticated;

create or replace function public.allocate_ap_to_job(p_ap_id uuid,p_job_id uuid,p_amount numeric,p_type text,p_notes text)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare u public.users%rowtype;a public.accounts_payable_entries%rowtype;j public.jobs%rowtype;allocated numeric;aid uuid;t text:=btrim(coalesce(p_type,''));begin
select * into u from public.users where auth_user_id=auth.uid() and active=true limit 1;if u.id is null or u.role not in ('owner','manager','accounting') then raise exception 'Not authorized';end if;
if p_ap_id is null or p_job_id is null or p_amount is null or p_amount<=0 then raise exception 'Choose a bill and job and enter a positive allocation';end if;if t not in ('materials','subcontractor','equipment','permit','other') then raise exception 'Invalid allocation type';end if;
select * into a from public.accounts_payable_entries where id=p_ap_id for update;if not found then raise exception 'AP bill not found';end if;if a.status='void' then raise exception 'Void AP bills cannot be allocated';end if;
select * into j from public.jobs where id=p_job_id for update;if not found then raise exception 'Job not found';end if;if j.status='cancelled' then raise exception 'Cancelled jobs cannot receive AP cost allocations';end if;if a.customer_id is not null and a.customer_id is distinct from j.customer_id then raise exception 'Bill customer does not match job customer';end if;
select coalesce(sum(amount),0) into allocated from public.job_cost_allocations where accounts_payable_entry_id=a.id;if allocated+p_amount>a.total then raise exception 'Allocation exceeds remaining bill total';end if;
insert into public.job_cost_allocations(accounts_payable_id,accounts_payable_entry_id,job_id,amount,allocation_type,notes,created_by) values(null,a.id,j.id,p_amount,t,nullif(btrim(coalesce(p_notes,'')),''),u.id) on conflict(accounts_payable_entry_id,job_id,allocation_type) do update set amount=public.job_cost_allocations.amount+excluded.amount,notes=coalesce(excluded.notes,public.job_cost_allocations.notes) returning id into aid;
insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(u.id,'allocate_ap_job_cost','job',j.id::text,jsonb_build_object('accounts_payable_entry_id',a.id,'previous_allocated_total',allocated,'bill_total',a.total),jsonb_build_object('allocation_id',aid,'accounts_payable_entry_id',a.id,'amount',p_amount,'type',t,'allocated_total',allocated+p_amount,'remaining_unallocated',a.total-(allocated+p_amount)));return aid;end;$$;
revoke all on function public.allocate_ap_to_job(uuid,uuid,numeric,text,text) from public;grant execute on function public.allocate_ap_to_job(uuid,uuid,numeric,text,text) to authenticated;
