create or replace function public.save_technician_skill_atomic(p_technician_id uuid,p_skill text,p_proficiency integer,p_certified boolean,p_certification_name text,p_certification_expires_on date)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare actor public.users%rowtype;tech public.users%rowtype;old_skill public.technician_skills%rowtype;saved_id uuid;allowed text[]:=array['Plumbing Service','Drain & Sewer','Water Heaters','Tankless','Boilers','Furnaces','Heat Pumps','Ductless Mini-Splits','Central AC','HVAC Service','HVAC Installation','Gas Piping','New Construction','IAQ'];begin
select * into actor from public.users where auth_user_id=auth.uid() and active=true limit 1;if actor.id is null or actor.role not in ('owner','manager') then raise exception 'Not authorized';end if;
if p_technician_id is null or not (p_skill=any(allowed)) or p_proficiency is null or p_proficiency<0 or p_proficiency>100 then raise exception 'Invalid technician skill';end if;
select * into tech from public.users where id=p_technician_id for update;if not found or tech.role<>'technician' or tech.active<>true then raise exception 'Active technician required';end if;
if coalesce(p_certified,false)=false and (nullif(btrim(coalesce(p_certification_name,'')),'') is not null or p_certification_expires_on is not null) then raise exception 'Certification details require Certified to be selected';end if;
select * into old_skill from public.technician_skills where technician_id=p_technician_id and skill=p_skill for update;
insert into public.technician_skills(technician_id,skill,proficiency,certified,certification_name,certification_expires_on,active) values(p_technician_id,p_skill,p_proficiency,coalesce(p_certified,false),case when coalesce(p_certified,false) then nullif(btrim(coalesce(p_certification_name,'')),'') else null end,case when coalesce(p_certified,false) then p_certification_expires_on else null end,true)
on conflict(technician_id,skill) do update set proficiency=excluded.proficiency,certified=excluded.certified,certification_name=excluded.certification_name,certification_expires_on=excluded.certification_expires_on,active=true returning id into saved_id;
insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(actor.id,'save_technician_skill','technician_skill',saved_id::text,case when old_skill.id is null then null else to_jsonb(old_skill) end,jsonb_build_object('technician_id',p_technician_id,'skill',p_skill,'proficiency',p_proficiency,'certified',coalesce(p_certified,false),'certification_name',case when coalesce(p_certified,false) then nullif(btrim(coalesce(p_certification_name,'')),'') else null end,'certification_expires_on',case when coalesce(p_certified,false) then p_certification_expires_on else null end,'active',true));return saved_id;end;$$;
revoke all on function public.save_technician_skill_atomic(uuid,text,integer,boolean,text,date) from public;grant execute on function public.save_technician_skill_atomic(uuid,text,integer,boolean,text,date) to authenticated;