create or replace function public.create_customer_atomic(p_name text,p_phone text,p_email text,p_service_address text,p_latitude numeric,p_longitude numeric)
returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_role text;v_actor uuid;v_id uuid;begin
v_role:=private.current_employee_role();if v_role not in ('owner','manager','csr_dispatch') then raise exception 'Not authorized';end if;select id into v_actor from public.users where auth_user_id=auth.uid() and active=true limit 1;if v_actor is null then raise exception 'Employee identity unavailable';end if;
if nullif(btrim(coalesce(p_name,'')),'') is null then raise exception 'Customer name is required';end if;if nullif(btrim(coalesce(p_service_address,'')),'') is null or p_latitude is null or p_longitude is null then raise exception 'Verified service address and coordinates are required';end if;if p_latitude<-90 or p_latitude>90 or p_longitude<-180 or p_longitude>180 then raise exception 'Invalid customer coordinates';end if;
insert into public.customers(name,phone,email,service_address,latitude,longitude) values(btrim(p_name),nullif(btrim(coalesce(p_phone,'')),''),nullif(btrim(coalesce(p_email,'')),''),btrim(p_service_address),p_latitude,p_longitude) returning id into v_id;
insert into public.audit_log(actor_user_id,action,entity_type,entity_id,after_data) values(v_actor,'create_customer','customer',v_id::text,jsonb_build_object('name',btrim(p_name),'phone',nullif(btrim(coalesce(p_phone,'')),''),'email',nullif(btrim(coalesce(p_email,'')),''),'service_address',btrim(p_service_address),'latitude',p_latitude,'longitude',p_longitude,'verified_address',true));return v_id;end;$$;
revoke all on function public.create_customer_atomic(text,text,text,text,numeric,numeric) from public;grant execute on function public.create_customer_atomic(text,text,text,text,numeric,numeric) to authenticated;

create or replace function public.update_customer_verified_address_atomic(p_customer_id uuid,p_service_address text,p_latitude numeric,p_longitude numeric)
returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_role text;v_actor uuid;v_old public.customers%rowtype;begin
v_role:=private.current_employee_role();if v_role not in ('owner','manager','csr_dispatch') then raise exception 'Not authorized';end if;select id into v_actor from public.users where auth_user_id=auth.uid() and active=true limit 1;if v_actor is null then raise exception 'Employee identity unavailable';end if;
if p_customer_id is null or nullif(btrim(coalesce(p_service_address,'')),'') is null or p_latitude is null or p_longitude is null then raise exception 'Verified customer address is required';end if;if p_latitude<-90 or p_latitude>90 or p_longitude<-180 or p_longitude>180 then raise exception 'Invalid customer coordinates';end if;
select * into v_old from public.customers where id=p_customer_id for update;if not found then raise exception 'Customer not found';end if;
update public.customers set service_address=btrim(p_service_address),latitude=p_latitude,longitude=p_longitude where id=p_customer_id;
insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(v_actor,'update_customer_verified_address','customer',p_customer_id::text,jsonb_build_object('service_address',v_old.service_address,'latitude',v_old.latitude,'longitude',v_old.longitude),jsonb_build_object('service_address',btrim(p_service_address),'latitude',p_latitude,'longitude',p_longitude,'verified_address',true));return p_customer_id;end;$$;
revoke all on function public.update_customer_verified_address_atomic(uuid,text,numeric,numeric) from public;grant execute on function public.update_customer_verified_address_atomic(uuid,text,numeric,numeric) to authenticated;