alter function public.create_job_atomic(uuid,text,text,timestamptz,timestamptz) rename to create_job_atomic_impl;
alter function public.reschedule_job_atomic(uuid,timestamptz,timestamptz) rename to reschedule_job_atomic_impl;
alter function public.cancel_job_atomic(uuid,text) rename to cancel_job_atomic_impl;
alter function public.assign_technician_atomic(uuid,uuid) rename to assign_technician_atomic_impl;
alter function public.approve_fleet_assignment_atomic(uuid,uuid,timestamptz,timestamptz,numeric,numeric,numeric,numeric,text,timestamptz,timestamptz) rename to approve_fleet_assignment_atomic_impl;

revoke all on function public.create_job_atomic_impl(uuid,text,text,timestamptz,timestamptz) from public,authenticated;
revoke all on function public.reschedule_job_atomic_impl(uuid,timestamptz,timestamptz) from public,authenticated;
revoke all on function public.cancel_job_atomic_impl(uuid,text) from public,authenticated;
revoke all on function public.assign_technician_atomic_impl(uuid,uuid) from public,authenticated;
revoke all on function public.approve_fleet_assignment_atomic_impl(uuid,uuid,timestamptz,timestamptz,numeric,numeric,numeric,numeric,text,timestamptz,timestamptz) from public,authenticated;

create function public.create_job_atomic(p_customer_id uuid,p_service_type text,p_service_summary text default null,p_scheduled_start timestamptz default null,p_scheduled_end timestamptz default null) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if not private.has_permission('manage_jobs') then raise exception 'Permission denied'; end if; return public.create_job_atomic_impl(p_customer_id,p_service_type,p_service_summary,p_scheduled_start,p_scheduled_end); end $$;
create function public.reschedule_job_atomic(p_job_id uuid,p_scheduled_start timestamptz,p_scheduled_end timestamptz default null) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if not private.has_permission('manage_schedule') then raise exception 'Permission denied'; end if; return public.reschedule_job_atomic_impl(p_job_id,p_scheduled_start,p_scheduled_end); end $$;
create function public.cancel_job_atomic(p_job_id uuid,p_reason text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if not private.has_permission('manage_jobs') then raise exception 'Permission denied'; end if; return public.cancel_job_atomic_impl(p_job_id,p_reason); end $$;
create function public.assign_technician_atomic(p_job_id uuid,p_technician_id uuid default null) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if not private.has_permission('manage_dispatch') then raise exception 'Permission denied'; end if; return public.assign_technician_atomic_impl(p_job_id,p_technician_id); end $$;
create function public.approve_fleet_assignment_atomic(p_job_id uuid,p_technician_id uuid,p_expected_scheduled_start timestamptz,p_expected_scheduled_end timestamptz,p_recommended_start numeric,p_recommended_finish numeric,p_drive_in_minutes numeric,p_drive_to_next_minutes numeric,p_routing_source text,p_service_day_start timestamptz,p_service_day_end timestamptz) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if not private.has_permission('manage_dispatch') then raise exception 'Permission denied'; end if; return public.approve_fleet_assignment_atomic_impl(p_job_id,p_technician_id,p_expected_scheduled_start,p_expected_scheduled_end,p_recommended_start,p_recommended_finish,p_drive_in_minutes,p_drive_to_next_minutes,p_routing_source,p_service_day_start,p_service_day_end); end $$;

revoke all on function public.create_job_atomic(uuid,text,text,timestamptz,timestamptz) from public; grant execute on function public.create_job_atomic(uuid,text,text,timestamptz,timestamptz) to authenticated;
revoke all on function public.reschedule_job_atomic(uuid,timestamptz,timestamptz) from public; grant execute on function public.reschedule_job_atomic(uuid,timestamptz,timestamptz) to authenticated;
revoke all on function public.cancel_job_atomic(uuid,text) from public; grant execute on function public.cancel_job_atomic(uuid,text) to authenticated;
revoke all on function public.assign_technician_atomic(uuid,uuid) from public; grant execute on function public.assign_technician_atomic(uuid,uuid) to authenticated;
revoke all on function public.approve_fleet_assignment_atomic(uuid,uuid,timestamptz,timestamptz,numeric,numeric,numeric,numeric,text,timestamptz,timestamptz) from public; grant execute on function public.approve_fleet_assignment_atomic(uuid,uuid,timestamptz,timestamptz,numeric,numeric,numeric,numeric,text,timestamptz,timestamptz) to authenticated;