-- Rename hardened implementations so public entrypoints can enforce configurable permissions.
alter function public.create_estimate_atomic(uuid) rename to create_estimate_atomic_impl;
alter function public.add_estimate_option_atomic(uuid,text,text,numeric,numeric,uuid) rename to add_estimate_option_atomic_impl;
alter function public.approve_estimate_option_internal(uuid,uuid) rename to approve_estimate_option_internal_impl;
alter function public.create_estimate_acceptance_link_atomic(uuid) rename to create_estimate_acceptance_link_atomic_impl;
alter function public.revoke_estimate_acceptance_link_atomic(uuid) rename to revoke_estimate_acceptance_link_atomic_impl;
alter function public.create_job_invoice_explicit(uuid,numeric,boolean) rename to create_job_invoice_explicit_impl;
alter function public.record_invoice_payment(uuid,numeric,text,text) rename to record_invoice_payment_impl;
alter function public.close_job_financially(uuid) rename to close_job_financially_impl;
alter function public.set_field_status_atomic(uuid,text,boolean) rename to set_field_status_atomic_impl;
alter function public.add_work_time_atomic(uuid,numeric) rename to add_work_time_atomic_impl;
alter function public.add_field_material_atomic(uuid,text,text,numeric,numeric) rename to add_field_material_atomic_impl;
alter function public.add_job_note_atomic(uuid,text,text) rename to add_job_note_atomic_impl;
alter function public.finalize_job_photo_atomic(uuid,text,text) rename to finalize_job_photo_atomic_impl;
alter function public.consume_inventory_for_job(uuid,uuid,numeric) rename to consume_inventory_for_job_impl;
alter function public.create_inventory_item_atomic(text,text,text,numeric,numeric,numeric) rename to create_inventory_item_atomic_impl;
alter function public.update_inventory_item_atomic(uuid,numeric,numeric,numeric,numeric,numeric,numeric) rename to update_inventory_item_atomic_impl;
alter function public.create_customer_atomic(text,text,text,text,numeric,numeric) rename to create_customer_atomic_impl;
alter function public.update_customer_verified_address_atomic(uuid,text,numeric,numeric) rename to update_customer_verified_address_atomic_impl;
alter function public.add_customer_equipment_atomic(uuid,text,text,text,text,text,date,date,date,date,text) rename to add_customer_equipment_atomic_impl;
alter function public.save_technician_skill_atomic(uuid,text,integer,boolean,text,date) rename to save_technician_skill_atomic_impl;
alter function public.create_purchase_order(uuid,uuid,text,timestamptz) rename to create_purchase_order_impl;
alter function public.receive_purchase_order_line(uuid,numeric,uuid) rename to receive_purchase_order_line_impl;
alter function public.finalize_purchase_order_document_atomic(uuid,text,text) rename to finalize_purchase_order_document_atomic_impl;
alter function public.review_and_approve_vendor_bill(uuid,text,date,date,numeric,numeric,numeric,text,text) rename to review_and_approve_vendor_bill_impl;
alter function public.reject_vendor_bill_atomic(uuid,text) rename to reject_vendor_bill_atomic_impl;
alter function public.record_ap_payment(uuid,numeric,timestamptz,text,text,text) rename to record_ap_payment_impl;
alter function public.allocate_ap_to_job(uuid,uuid,numeric,text,text) rename to allocate_ap_to_job_impl;
alter function public.review_price_book_learning_proposal(uuid,text) rename to review_price_book_learning_proposal_impl;

-- Internal implementations are not directly invokable by clients.
revoke all on function public.create_estimate_atomic_impl(uuid) from public,authenticated;
revoke all on function public.add_estimate_option_atomic_impl(uuid,text,text,numeric,numeric,uuid) from public,authenticated;
revoke all on function public.approve_estimate_option_internal_impl(uuid,uuid) from public,authenticated;
revoke all on function public.create_estimate_acceptance_link_atomic_impl(uuid) from public,authenticated;
revoke all on function public.revoke_estimate_acceptance_link_atomic_impl(uuid) from public,authenticated;
revoke all on function public.create_job_invoice_explicit_impl(uuid,numeric,boolean) from public,authenticated;
revoke all on function public.record_invoice_payment_impl(uuid,numeric,text,text) from public,authenticated;
revoke all on function public.close_job_financially_impl(uuid) from public,authenticated;
revoke all on function public.set_field_status_atomic_impl(uuid,text,boolean) from public,authenticated;
revoke all on function public.add_work_time_atomic_impl(uuid,numeric) from public,authenticated;
revoke all on function public.add_field_material_atomic_impl(uuid,text,text,numeric,numeric) from public,authenticated;
revoke all on function public.add_job_note_atomic_impl(uuid,text,text) from public,authenticated;
revoke all on function public.finalize_job_photo_atomic_impl(uuid,text,text) from public,authenticated;
revoke all on function public.consume_inventory_for_job_impl(uuid,uuid,numeric) from public,authenticated;
revoke all on function public.create_inventory_item_atomic_impl(text,text,text,numeric,numeric,numeric) from public,authenticated;
revoke all on function public.update_inventory_item_atomic_impl(uuid,numeric,numeric,numeric,numeric,numeric,numeric) from public,authenticated;
revoke all on function public.create_customer_atomic_impl(text,text,text,text,numeric,numeric) from public,authenticated;
revoke all on function public.update_customer_verified_address_atomic_impl(uuid,text,numeric,numeric) from public,authenticated;
revoke all on function public.add_customer_equipment_atomic_impl(uuid,text,text,text,text,text,date,date,date,date,text) from public,authenticated;
revoke all on function public.save_technician_skill_atomic_impl(uuid,text,integer,boolean,text,date) from public,authenticated;
revoke all on function public.create_purchase_order_impl(uuid,uuid,text,timestamptz) from public,authenticated;
revoke all on function public.receive_purchase_order_line_impl(uuid,numeric,uuid) from public,authenticated;
revoke all on function public.finalize_purchase_order_document_atomic_impl(uuid,text,text) from public,authenticated;
revoke all on function public.review_and_approve_vendor_bill_impl(uuid,text,date,date,numeric,numeric,numeric,text,text) from public,authenticated;
revoke all on function public.reject_vendor_bill_atomic_impl(uuid,text) from public,authenticated;
revoke all on function public.record_ap_payment_impl(uuid,numeric,timestamptz,text,text,text) from public,authenticated;
revoke all on function public.allocate_ap_to_job_impl(uuid,uuid,numeric,text,text) from public,authenticated;
revoke all on function public.review_price_book_learning_proposal_impl(uuid,text) from public,authenticated;

-- Estimates.
create function public.create_estimate_atomic(p_job_id uuid) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_estimates') then raise exception 'Permission denied'; end if; return public.create_estimate_atomic_impl(p_job_id); end$$;
create function public.add_estimate_option_atomic(p_estimate_id uuid,p_tier text,p_description text,p_price numeric,p_cost numeric,p_price_book_tier_id uuid) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_estimates') then raise exception 'Permission denied'; end if; return public.add_estimate_option_atomic_impl(p_estimate_id,p_tier,p_description,p_price,p_cost,p_price_book_tier_id); end$$;
create function public.approve_estimate_option_internal(p_estimate_id uuid,p_option_id uuid) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_estimates') then raise exception 'Permission denied'; end if; return public.approve_estimate_option_internal_impl(p_estimate_id,p_option_id); end$$;
create function public.create_estimate_acceptance_link_atomic(p_estimate_id uuid) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_estimates') then raise exception 'Permission denied'; end if; return public.create_estimate_acceptance_link_atomic_impl(p_estimate_id); end$$;
create function public.revoke_estimate_acceptance_link_atomic(p_link_id uuid) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_estimates') then raise exception 'Permission denied'; end if; return public.revoke_estimate_acceptance_link_atomic_impl(p_link_id); end$$;

-- Billing.
create function public.create_job_invoice_explicit(p_job_id uuid,p_requested_total numeric,p_owner_price_exception boolean) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_billing') then raise exception 'Permission denied'; end if; return public.create_job_invoice_explicit_impl(p_job_id,p_requested_total,p_owner_price_exception); end$$;
create function public.record_invoice_payment(p_invoice_id uuid,p_amount numeric,p_method text,p_reference text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_billing') then raise exception 'Permission denied'; end if; return public.record_invoice_payment_impl(p_invoice_id,p_amount,p_method,p_reference); end$$;
create function public.close_job_financially(p_job_id uuid) returns boolean language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_billing') then raise exception 'Permission denied'; end if; return public.close_job_financially_impl(p_job_id); end$$;

-- Field workflow.
create function public.set_field_status_atomic(p_job_id uuid,p_requested_status text,p_no_materials boolean) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return public.set_field_status_atomic_impl(p_job_id,p_requested_status,p_no_materials); end$$;
create function public.add_work_time_atomic(p_job_id uuid,p_hours numeric) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return public.add_work_time_atomic_impl(p_job_id,p_hours); end$$;
create function public.add_field_material_atomic(p_job_id uuid,p_sku text,p_description text,p_quantity numeric,p_unit_cost numeric) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return public.add_field_material_atomic_impl(p_job_id,p_sku,p_description,p_quantity,p_unit_cost); end$$;
create function public.add_job_note_atomic(p_job_id uuid,p_note_type text,p_note text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return public.add_job_note_atomic_impl(p_job_id,p_note_type,p_note); end$$;
create function public.finalize_job_photo_atomic(p_job_id uuid,p_storage_path text,p_caption text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return public.finalize_job_photo_atomic_impl(p_job_id,p_storage_path,p_caption); end$$;
create function public.consume_inventory_for_job(p_job_id uuid,p_inventory_item_id uuid,p_quantity numeric) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return public.consume_inventory_for_job_impl(p_job_id,p_inventory_item_id,p_quantity); end$$;

-- Inventory/CRM/team.
create function public.create_inventory_item_atomic(p_sku text,p_description text,p_location text,p_on_hand numeric,p_reorder_point numeric,p_unit_cost numeric) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_inventory') then raise exception 'Permission denied'; end if; return public.create_inventory_item_atomic_impl(p_sku,p_description,p_location,p_on_hand,p_reorder_point,p_unit_cost); end$$;
create function public.update_inventory_item_atomic(p_id uuid,p_expected_on_hand numeric,p_expected_reorder_point numeric,p_expected_unit_cost numeric,p_on_hand numeric,p_reorder_point numeric,p_unit_cost numeric) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_inventory') then raise exception 'Permission denied'; end if; return public.update_inventory_item_atomic_impl(p_id,p_expected_on_hand,p_expected_reorder_point,p_expected_unit_cost,p_on_hand,p_reorder_point,p_unit_cost); end$$;
create function public.create_customer_atomic(p_name text,p_phone text,p_email text,p_service_address text,p_latitude numeric,p_longitude numeric) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_customers') then raise exception 'Permission denied'; end if; return public.create_customer_atomic_impl(p_name,p_phone,p_email,p_service_address,p_latitude,p_longitude); end$$;
create function public.update_customer_verified_address_atomic(p_customer_id uuid,p_service_address text,p_latitude numeric,p_longitude numeric) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_customers') then raise exception 'Permission denied'; end if; return public.update_customer_verified_address_atomic_impl(p_customer_id,p_service_address,p_latitude,p_longitude); end$$;
create function public.add_customer_equipment_atomic(p_customer_id uuid,p_equipment_type text,p_manufacturer text,p_model_number text,p_serial_number text,p_location text,p_installed_on date,p_warranty_expires_on date,p_last_service_on date,p_next_maintenance_on date,p_notes text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not (private.has_permission('manage_customers') or private.has_permission('field_app')) then raise exception 'Permission denied'; end if; return public.add_customer_equipment_atomic_impl(p_customer_id,p_equipment_type,p_manufacturer,p_model_number,p_serial_number,p_location,p_installed_on,p_warranty_expires_on,p_last_service_on,p_next_maintenance_on,p_notes); end$$;
create function public.save_technician_skill_atomic(p_technician_id uuid,p_skill text,p_proficiency integer,p_certified boolean,p_certification_name text,p_certification_expires_on date) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_team') then raise exception 'Permission denied'; end if; return public.save_technician_skill_atomic_impl(p_technician_id,p_skill,p_proficiency,p_certified,p_certification_name,p_certification_expires_on); end$$;

-- Purchasing/accounting.
create function public.create_purchase_order(p_supplier_id uuid,p_customer_id uuid,p_notes text,p_expected_at timestamptz) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_purchasing') then raise exception 'Permission denied'; end if; return public.create_purchase_order_impl(p_supplier_id,p_customer_id,p_notes,p_expected_at); end$$;
create function public.receive_purchase_order_line(p_line_id uuid,p_quantity numeric,p_location_id uuid) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_purchasing') then raise exception 'Permission denied'; end if; return public.receive_purchase_order_line_impl(p_line_id,p_quantity,p_location_id); end$$;
create function public.finalize_purchase_order_document_atomic(p_purchase_order_id uuid,p_storage_path text,p_file_name text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_purchasing') then raise exception 'Permission denied'; end if; return public.finalize_purchase_order_document_atomic_impl(p_purchase_order_id,p_storage_path,p_file_name); end$$;
create function public.review_and_approve_vendor_bill(p_bill_id uuid,p_invoice_number text,p_invoice_date date,p_due_date date,p_subtotal numeric,p_tax numeric,p_total numeric,p_account_code text,p_memo text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_accounting') then raise exception 'Permission denied'; end if; return public.review_and_approve_vendor_bill_impl(p_bill_id,p_invoice_number,p_invoice_date,p_due_date,p_subtotal,p_tax,p_total,p_account_code,p_memo); end$$;
create function public.reject_vendor_bill_atomic(p_bill_id uuid,p_reason text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_accounting') then raise exception 'Permission denied'; end if; return public.reject_vendor_bill_atomic_impl(p_bill_id,p_reason); end$$;
create function public.record_ap_payment(p_ap_id uuid,p_amount numeric,p_paid_at timestamptz,p_payment_method text,p_reference text,p_notes text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_accounting') then raise exception 'Permission denied'; end if; return public.record_ap_payment_impl(p_ap_id,p_amount,p_paid_at,p_payment_method,p_reference,p_notes); end$$;
create function public.allocate_ap_to_job(p_ap_id uuid,p_job_id uuid,p_amount numeric,p_type text,p_notes text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_accounting') then raise exception 'Permission denied'; end if; return public.allocate_ap_to_job_impl(p_ap_id,p_job_id,p_amount,p_type,p_notes); end$$;
create function public.review_price_book_learning_proposal(p_proposal_id uuid,p_decision text) returns void language plpgsql security definer set search_path=public,private,pg_temp as $$begin if not private.has_permission('manage_pricebook') then raise exception 'Permission denied'; end if; perform public.review_price_book_learning_proposal_impl(p_proposal_id,p_decision); end$$;

-- Only authenticated users can call public permission-gated entrypoints.
grant execute on function public.create_estimate_atomic(uuid),public.add_estimate_option_atomic(uuid,text,text,numeric,numeric,uuid),public.approve_estimate_option_internal(uuid,uuid),public.create_estimate_acceptance_link_atomic(uuid),public.revoke_estimate_acceptance_link_atomic(uuid),public.create_job_invoice_explicit(uuid,numeric,boolean),public.record_invoice_payment(uuid,numeric,text,text),public.close_job_financially(uuid),public.set_field_status_atomic(uuid,text,boolean),public.add_work_time_atomic(uuid,numeric),public.add_field_material_atomic(uuid,text,text,numeric,numeric),public.add_job_note_atomic(uuid,text,text),public.finalize_job_photo_atomic(uuid,text,text),public.consume_inventory_for_job(uuid,uuid,numeric),public.create_inventory_item_atomic(text,text,text,numeric,numeric,numeric),public.update_inventory_item_atomic(uuid,numeric,numeric,numeric,numeric,numeric,numeric),public.create_customer_atomic(text,text,text,text,numeric,numeric),public.update_customer_verified_address_atomic(uuid,text,numeric,numeric),public.add_customer_equipment_atomic(uuid,text,text,text,text,text,date,date,date,date,text),public.save_technician_skill_atomic(uuid,text,integer,boolean,text,date),public.create_purchase_order(uuid,uuid,text,timestamptz),public.receive_purchase_order_line(uuid,numeric,uuid),public.finalize_purchase_order_document_atomic(uuid,text,text),public.review_and_approve_vendor_bill(uuid,text,date,date,numeric,numeric,numeric,text,text),public.reject_vendor_bill_atomic(uuid,text),public.record_ap_payment(uuid,numeric,timestamptz,text,text,text),public.allocate_ap_to_job(uuid,uuid,numeric,text,text),public.review_price_book_learning_proposal(uuid,text) to authenticated;
revoke all on function public.create_estimate_atomic(uuid),public.add_estimate_option_atomic(uuid,text,text,numeric,numeric,uuid),public.approve_estimate_option_internal(uuid,uuid),public.create_estimate_acceptance_link_atomic(uuid),public.revoke_estimate_acceptance_link_atomic(uuid),public.create_job_invoice_explicit(uuid,numeric,boolean),public.record_invoice_payment(uuid,numeric,text,text),public.close_job_financially(uuid),public.set_field_status_atomic(uuid,text,boolean),public.add_work_time_atomic(uuid,numeric),public.add_field_material_atomic(uuid,text,text,numeric,numeric),public.add_job_note_atomic(uuid,text,text),public.finalize_job_photo_atomic(uuid,text,text),public.consume_inventory_for_job(uuid,uuid,numeric),public.create_inventory_item_atomic(text,text,text,numeric,numeric,numeric),public.update_inventory_item_atomic(uuid,numeric,numeric,numeric,numeric,numeric,numeric),public.create_customer_atomic(text,text,text,text,numeric,numeric),public.update_customer_verified_address_atomic(uuid,text,numeric,numeric),public.add_customer_equipment_atomic(uuid,text,text,text,text,text,date,date,date,date,text),public.save_technician_skill_atomic(uuid,text,integer,boolean,text,date),public.create_purchase_order(uuid,uuid,text,timestamptz),public.receive_purchase_order_line(uuid,numeric,uuid),public.finalize_purchase_order_document_atomic(uuid,text,text),public.review_and_approve_vendor_bill(uuid,text,date,date,numeric,numeric,numeric,text,text),public.reject_vendor_bill_atomic(uuid,text),public.record_ap_payment(uuid,numeric,timestamptz,text,text,text),public.allocate_ap_to_job(uuid,uuid,numeric,text,text),public.review_price_book_learning_proposal(uuid,text) from public;