create or replace function public.add_purchase_order_line_atomic(p_purchase_order_id uuid,p_inventory_item_id uuid,p_description text,p_quantity numeric,p_unit_cost numeric) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare u public.users%rowtype;po public.purchase_orders%rowtype;i public.inventory_items%rowtype;rid uuid;d text:=btrim(coalesce(p_description,''));begin
select * into u from public.users where auth_user_id=auth.uid() and active=true limit 1;if u.id is null or u.role not in ('owner','manager','accounting') or not private.has_permission('manage_purchasing') then raise exception 'Permission denied';end if;if p_purchase_order_id is null or p_quantity is null or p_quantity<=0 or p_unit_cost is null or p_unit_cost<0 then raise exception 'Valid PO, quantity and cost required';end if;select * into po from public.purchase_orders where id=p_purchase_order_id for update;if not found then raise exception 'Purchase order not found';end if;if po.status not in ('draft','submitted','partial') then raise exception 'Purchase order can no longer be edited';end if;if p_inventory_item_id is not null then select * into i from public.inventory_items where id=p_inventory_item_id;if not found then raise exception 'Inventory item not found';end if;if d='' then d:=i.description;end if;end if;if d='' then raise exception 'Description required';end if;if length(d)>500 then raise exception 'Description is too long';end if;insert into public.purchase_order_items(purchase_order_id,inventory_item_id,description,quantity,unit_cost) values(po.id,p_inventory_item_id,d,p_quantity,p_unit_cost) returning id into rid;insert into public.audit_log(actor_user_id,action,entity_type,entity_id,after_data) values(u.id,'add_purchase_order_line','purchase_order',po.id::text,jsonb_build_object('line_id',rid,'inventory_item_id',p_inventory_item_id,'description',d,'quantity',p_quantity,'unit_cost',p_unit_cost));return rid;end$$;

create or replace function public.update_purchase_order_line_atomic(p_line_id uuid,p_quantity numeric,p_unit_cost numeric,p_description text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare u public.users%rowtype;x public.purchase_order_items%rowtype;po public.purchase_orders%rowtype;d text:=btrim(coalesce(p_description,''));begin
select * into u from public.users where auth_user_id=auth.uid() and active=true limit 1;if u.id is null or u.role not in ('owner','manager','accounting') or not private.has_permission('manage_purchasing') then raise exception 'Permission denied';end if;if p_line_id is null or p_quantity is null or p_quantity<=0 or p_unit_cost is null or p_unit_cost<0 or d='' or length(d)>500 then raise exception 'Valid line values required';end if;select * into x from public.purchase_order_items where id=p_line_id for update;if not found then raise exception 'Purchase order line not found';end if;select * into po from public.purchase_orders where id=x.purchase_order_id for update;if po.status not in ('draft','submitted','partial') then raise exception 'Purchase order can no longer be edited';end if;if x.received_quantity>0 then raise exception 'Received lines are locked; use a correction workflow rather than rewriting receipt history';end if;update public.purchase_order_items set description=d,quantity=p_quantity,unit_cost=p_unit_cost where id=x.id;insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(u.id,'update_purchase_order_line','purchase_order',po.id::text,jsonb_build_object('line_id',x.id,'description',x.description,'quantity',x.quantity,'unit_cost',x.unit_cost),jsonb_build_object('line_id',x.id,'description',d,'quantity',p_quantity,'unit_cost',p_unit_cost));return x.id;end$$;

create or replace function public.remove_purchase_order_line_atomic(p_line_id uuid,p_reason text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare u public.users%rowtype;x public.purchase_order_items%rowtype;po public.purchase_orders%rowtype;r text:=btrim(coalesce(p_reason,''));begin
select * into u from public.users where auth_user_id=auth.uid() and active=true limit 1;if u.id is null or u.role not in ('owner','manager','accounting') or not private.has_permission('manage_purchasing') then raise exception 'Permission denied';end if;if length(r)<3 or length(r)>1000 then raise exception 'Removal reason required';end if;select * into x from public.purchase_order_items where id=p_line_id for update;if not found then raise exception 'Purchase order line not found';end if;select * into po from public.purchase_orders where id=x.purchase_order_id for update;if po.status not in ('draft','submitted','partial') then raise exception 'Purchase order can no longer be edited';end if;if x.received_quantity>0 then raise exception 'Received lines cannot be removed';end if;delete from public.purchase_order_items where id=x.id;insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(u.id,'remove_purchase_order_line','purchase_order',po.id::text,to_jsonb(x),jsonb_build_object('removed',true,'reason',r));return x.id;end$$;

revoke all on function public.add_purchase_order_line_atomic(uuid,uuid,text,numeric,numeric),public.update_purchase_order_line_atomic(uuid,numeric,numeric,text),public.remove_purchase_order_line_atomic(uuid,text) from public,anon;
grant execute on function public.add_purchase_order_line_atomic(uuid,uuid,text,numeric,numeric),public.update_purchase_order_line_atomic(uuid,numeric,numeric,text),public.remove_purchase_order_line_atomic(uuid,text) to authenticated;