create or replace function public.create_job_atomic_impl(p_customer_id uuid, p_service_type text, p_service_summary text default null::text, p_scheduled_start timestamptz default null, p_scheduled_end timestamptz default null) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_actor uuid;v_job_id uuid;v_status text;begin
select id into v_actor from public.users where auth_user_id=auth.uid() and active=true limit 1;if v_actor is null then raise exception 'Employee identity unavailable';end if;
if p_customer_id is null or not exists(select 1 from public.customers where id=p_customer_id) then raise exception 'Customer required';end if;
if p_service_type is null or p_service_type not in ('Plumbing Service','Drain & Sewer','Water Heaters','Tankless','Boilers','Furnaces','Heat Pumps','Ductless Mini-Splits','Central AC','HVAC Service','HVAC Installation','Gas Piping','New Construction','IAQ') then raise exception 'Service type required';end if;
if p_scheduled_end is not null and p_scheduled_start is null then raise exception 'Schedule start required when schedule end is provided';end if;if p_scheduled_start is not null and p_scheduled_end is not null and p_scheduled_end<=p_scheduled_start then raise exception 'Schedule end must be after start';end if;if length(coalesce(p_service_summary,''))>5000 then raise exception 'Service summary is too long';end if;
v_status:=case when p_scheduled_start is null then 'booked' else 'scheduled' end;
insert into public.jobs(customer_id,created_by,service_type,service_summary,status,scheduled_start,scheduled_end) values(p_customer_id,v_actor,p_service_type,nullif(btrim(coalesce(p_service_summary,'')),''),v_status,p_scheduled_start,p_scheduled_end) returning id into v_job_id;
insert into public.audit_log(actor_user_id,action,entity_type,entity_id,after_data) values(v_actor,'create_job','job',v_job_id::text,jsonb_build_object('customer_id',p_customer_id,'service_type',p_service_type,'status',v_status,'scheduled_start',p_scheduled_start,'scheduled_end',p_scheduled_end));return v_job_id;end$$;

create or replace function public.reschedule_job_atomic_impl(p_job_id uuid,p_scheduled_start timestamptz,p_scheduled_end timestamptz default null) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_actor uuid;v_job public.jobs%rowtype;v_next_status text;begin
select id into v_actor from public.users where auth_user_id=auth.uid() and active=true limit 1;if v_actor is null then raise exception 'Employee identity unavailable';end if;
if p_scheduled_start is null then raise exception 'Schedule start required';end if;if p_scheduled_end is not null and p_scheduled_end<=p_scheduled_start then raise exception 'Schedule end must be after start';end if;
select * into v_job from public.jobs where id=p_job_id for update;if not found then raise exception 'Job not found';end if;if v_job.status not in ('booked','scheduled','dispatched') then raise exception 'Schedule cannot be changed after field work starts or the job is closed';end if;
v_next_status:=case when v_job.technician_id is null then 'scheduled' else 'dispatched' end;update public.jobs set scheduled_start=p_scheduled_start,scheduled_end=p_scheduled_end,status=v_next_status where id=p_job_id;
insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(v_actor,'reschedule_job','job',p_job_id::text,jsonb_build_object('scheduled_start',v_job.scheduled_start,'scheduled_end',v_job.scheduled_end,'status',v_job.status),jsonb_build_object('scheduled_start',p_scheduled_start,'scheduled_end',p_scheduled_end,'status',v_next_status,'source','dispatcher'));return p_job_id;end$$;

create or replace function public.cancel_job_atomic_impl(p_job_id uuid,p_reason text) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_actor uuid;v_job public.jobs%rowtype;v_reason text;begin
select id into v_actor from public.users where auth_user_id=auth.uid() and active=true limit 1;if v_actor is null then raise exception 'Employee identity unavailable';end if;v_reason:=btrim(coalesce(p_reason,''));if length(v_reason)<3 then raise exception 'Cancellation reason required';end if;if length(v_reason)>1000 then raise exception 'Cancellation reason is too long';end if;
select * into v_job from public.jobs where id=p_job_id for update;if not found then raise exception 'Job not found';end if;if v_job.status not in ('booked','scheduled','dispatched') then raise exception 'Job cannot be cancelled after field work starts or after closeout';end if;update public.jobs set status='cancelled',technician_id=null where id=p_job_id;
insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(v_actor,'cancel_job','job',p_job_id::text,jsonb_build_object('status',v_job.status,'technician_id',v_job.technician_id,'scheduled_start',v_job.scheduled_start,'scheduled_end',v_job.scheduled_end),jsonb_build_object('status','cancelled','reason',v_reason,'source','dispatcher'));return p_job_id;end$$;

create or replace function public.assign_technician_atomic_impl(p_job_id uuid,p_technician_id uuid default null) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_actor uuid;v_job public.jobs%rowtype;v_tech public.users%rowtype;v_skill public.technician_skills%rowtype;v_next_status text;v_target_start timestamptz;v_target_end timestamptz;v_conflict uuid;begin
select id into v_actor from public.users where auth_user_id=auth.uid() and active=true limit 1;if v_actor is null then raise exception 'Employee identity unavailable';end if;
select * into v_job from public.jobs where id=p_job_id for update;if not found then raise exception 'Job not found';end if;if v_job.status not in ('booked','scheduled','dispatched') then raise exception 'Technician assignment cannot be changed after field work starts or the job is closed';end if;
if p_technician_id is not null then select * into v_tech from public.users where id=p_technician_id and role='technician' and active=true for update;if not found then raise exception 'Active technician required';end if;if v_job.service_type is not null then select * into v_skill from public.technician_skills where technician_id=p_technician_id and skill=v_job.service_type and active=true limit 1;if not found then raise exception 'Technician is not eligible for this service';end if;if v_skill.certification_expires_on is not null and v_skill.certification_expires_on<current_date then raise exception 'Technician certification has expired';end if;end if;
v_target_start:=v_job.scheduled_start;if v_target_start is not null then v_target_end:=coalesce(v_job.scheduled_end,v_target_start+make_interval(mins=>greatest(coalesce(v_job.expected_duration_minutes,120),1)));select j.id into v_conflict from public.jobs j where j.technician_id=p_technician_id and j.id<>p_job_id and j.status in ('booked','scheduled','dispatched') and j.scheduled_start is not null and tstzrange(j.scheduled_start,coalesce(j.scheduled_end,j.scheduled_start+make_interval(mins=>greatest(coalesce(j.expected_duration_minutes,120),1))),'[)') && tstzrange(v_target_start,v_target_end,'[)') order by j.scheduled_start limit 1 for update;if v_conflict is not null then raise exception 'Technician already has an overlapping scheduled job';end if;end if;v_next_status:='dispatched';else v_next_status:='scheduled';end if;
update public.jobs set technician_id=p_technician_id,status=v_next_status where id=p_job_id;insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(v_actor,case when p_technician_id is null then 'unassign_technician' else 'assign_technician' end,'job',p_job_id::text,jsonb_build_object('technician_id',v_job.technician_id,'status',v_job.status),jsonb_build_object('technician_id',p_technician_id,'status',v_next_status,'source','manual_dispatch','schedule_overlap_checked',p_technician_id is not null and v_target_start is not null,'scheduled_start',v_target_start,'scheduled_end',v_target_end));return p_job_id;end$$;

create or replace function public.approve_fleet_assignment_atomic_impl(p_job_id uuid,p_technician_id uuid,p_expected_scheduled_start timestamptz,p_expected_scheduled_end timestamptz,p_recommended_start numeric,p_recommended_finish numeric,p_drive_in_minutes numeric,p_drive_to_next_minutes numeric,p_routing_source text,p_service_day_start timestamptz,p_service_day_end timestamptz) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_actor uuid;v_job public.jobs%rowtype;v_tech public.users%rowtype;v_skill public.technician_skills%rowtype;begin
select id into v_actor from public.users where auth_user_id=auth.uid() and active=true limit 1;if v_actor is null then raise exception 'Employee identity unavailable';end if;if p_technician_id is null then raise exception 'Technician required';end if;if p_recommended_start is null or p_recommended_finish is null or p_recommended_finish<=p_recommended_start then raise exception 'Invalid fleet recommendation';end if;
select * into v_job from public.jobs where id=p_job_id for update;if not found then raise exception 'Job not found';end if;if v_job.technician_id is not null then raise exception 'Job is already assigned; refresh the fleet plan';end if;if v_job.status not in ('booked','scheduled','dispatched') then raise exception 'Job can no longer be dispatched';end if;if v_job.scheduled_start is distinct from p_expected_scheduled_start or v_job.scheduled_end is distinct from p_expected_scheduled_end then raise exception 'Job schedule changed; refresh the fleet plan';end if;
select * into v_tech from public.users where id=p_technician_id and role='technician' and active=true;if not found then raise exception 'Active technician required';end if;if v_job.service_type is not null then select * into v_skill from public.technician_skills where technician_id=p_technician_id and skill=v_job.service_type and active=true limit 1;if not found then raise exception 'Technician is no longer eligible for this service';end if;if v_skill.certification_expires_on is not null and v_skill.certification_expires_on<current_date then raise exception 'Technician certification has expired';end if;end if;
update public.jobs set technician_id=p_technician_id,status='dispatched' where id=p_job_id;insert into public.audit_log(actor_user_id,action,entity_type,entity_id,before_data,after_data) values(v_actor,'approve_fleet_assignment','job',p_job_id::text,jsonb_build_object('technician_id',v_job.technician_id,'status',v_job.status,'scheduled_start',v_job.scheduled_start,'scheduled_end',v_job.scheduled_end),jsonb_build_object('technician_id',p_technician_id,'status','dispatched','scheduled_start',v_job.scheduled_start,'scheduled_end',v_job.scheduled_end,'service_day_start',p_service_day_start,'service_day_end',p_service_day_end,'recommended_start',p_recommended_start,'recommended_finish',p_recommended_finish,'drive_in_minutes',p_drive_in_minutes,'drive_to_next_minutes',p_drive_to_next_minutes,'routing_source',p_routing_source,'source','fleet_optimizer'));return p_job_id;end$$;

revoke all on function public.create_job_atomic_impl(uuid,text,text,timestamptz,timestamptz),public.reschedule_job_atomic_impl(uuid,timestamptz,timestamptz),public.cancel_job_atomic_impl(uuid,text),public.assign_technician_atomic_impl(uuid,uuid),public.approve_fleet_assignment_atomic_impl(uuid,uuid,timestamptz,timestamptz,numeric,numeric,numeric,numeric,text,timestamptz,timestamptz) from public,anon,authenticated;
