-- Move privileged dispatch/field implementations out of the exposed public schema.
-- Public RPC names stay stable and run as the caller; private implementations retain
-- SECURITY DEFINER behavior and are reachable only through the authenticated wrapper.

alter function public.add_field_material_atomic_impl(uuid,text,text,numeric,numeric) set schema private;
alter function public.add_job_note_atomic_impl(uuid,text,text) set schema private;
alter function public.add_work_time_atomic_impl(uuid,numeric) set schema private;
alter function public.approve_fleet_assignment_atomic_impl(uuid,uuid,timestamptz,timestamptz,numeric,numeric,numeric,numeric,text,timestamptz,timestamptz) set schema private;
alter function public.assign_technician_atomic_impl(uuid,uuid) set schema private;
alter function public.cancel_job_atomic_impl(uuid,text) set schema private;
alter function public.consume_inventory_for_job_impl(uuid,uuid,numeric) set schema private;
alter function public.create_job_atomic_impl(uuid,text,text,timestamptz,timestamptz) set schema private;
alter function public.finalize_job_photo_atomic_impl(uuid,text,text) set schema private;
alter function public.reschedule_job_atomic_impl(uuid,timestamptz,timestamptz) set schema private;
alter function public.set_field_status_atomic_impl(uuid,text,boolean) set schema private;

grant usage on schema private to authenticated;
grant execute on function private.add_field_material_atomic_impl(uuid,text,text,numeric,numeric),private.add_job_note_atomic_impl(uuid,text,text),private.add_work_time_atomic_impl(uuid,numeric),private.approve_fleet_assignment_atomic_impl(uuid,uuid,timestamptz,timestamptz,numeric,numeric,numeric,numeric,text,timestamptz,timestamptz),private.assign_technician_atomic_impl(uuid,uuid),private.cancel_job_atomic_impl(uuid,text),private.consume_inventory_for_job_impl(uuid,uuid,numeric),private.create_job_atomic_impl(uuid,text,text,timestamptz,timestamptz),private.finalize_job_photo_atomic_impl(uuid,text,text),private.reschedule_job_atomic_impl(uuid,timestamptz,timestamptz),private.set_field_status_atomic_impl(uuid,text,boolean) to authenticated;

create or replace function public.add_field_material_atomic(p_job_id uuid,p_sku text,p_description text,p_quantity numeric,p_unit_cost numeric) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return private.add_field_material_atomic_impl(p_job_id,p_sku,p_description,p_quantity,p_unit_cost); end$$;
create or replace function public.add_job_note_atomic(p_job_id uuid,p_note_type text,p_note text) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return private.add_job_note_atomic_impl(p_job_id,p_note_type,p_note); end$$;
create or replace function public.add_work_time_atomic(p_job_id uuid,p_hours numeric) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return private.add_work_time_atomic_impl(p_job_id,p_hours); end$$;
create or replace function public.approve_fleet_assignment_atomic(p_job_id uuid,p_technician_id uuid,p_expected_scheduled_start timestamptz,p_expected_scheduled_end timestamptz,p_recommended_start numeric,p_recommended_finish numeric,p_drive_in_minutes numeric,p_drive_to_next_minutes numeric,p_routing_source text,p_service_day_start timestamptz,p_service_day_end timestamptz) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('manage_dispatch') then raise exception 'Permission denied'; end if; return private.approve_fleet_assignment_atomic_impl(p_job_id,p_technician_id,p_expected_scheduled_start,p_expected_scheduled_end,p_recommended_start,p_recommended_finish,p_drive_in_minutes,p_drive_to_next_minutes,p_routing_source,p_service_day_start,p_service_day_end); end$$;
create or replace function public.assign_technician_atomic(p_job_id uuid,p_technician_id uuid default null) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('manage_dispatch') then raise exception 'Permission denied'; end if; return private.assign_technician_atomic_impl(p_job_id,p_technician_id); end$$;
create or replace function public.cancel_job_atomic(p_job_id uuid,p_reason text) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('manage_jobs') then raise exception 'Permission denied'; end if; return private.cancel_job_atomic_impl(p_job_id,p_reason); end$$;
create or replace function public.consume_inventory_for_job(p_job_id uuid,p_inventory_item_id uuid,p_quantity numeric) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return private.consume_inventory_for_job_impl(p_job_id,p_inventory_item_id,p_quantity); end$$;
create or replace function public.create_job_atomic(p_customer_id uuid,p_service_type text,p_service_summary text default null,p_scheduled_start timestamptz default null,p_scheduled_end timestamptz default null) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('manage_jobs') then raise exception 'Permission denied'; end if; return private.create_job_atomic_impl(p_customer_id,p_service_type,p_service_summary,p_scheduled_start,p_scheduled_end); end$$;
create or replace function public.finalize_job_photo_atomic(p_job_id uuid,p_storage_path text,p_caption text) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return private.finalize_job_photo_atomic_impl(p_job_id,p_storage_path,p_caption); end$$;
create or replace function public.reschedule_job_atomic(p_job_id uuid,p_scheduled_start timestamptz,p_scheduled_end timestamptz default null) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('manage_schedule') then raise exception 'Permission denied'; end if; return private.reschedule_job_atomic_impl(p_job_id,p_scheduled_start,p_scheduled_end); end$$;
create or replace function public.set_field_status_atomic(p_job_id uuid,p_requested_status text,p_no_materials boolean) returns uuid language plpgsql security invoker set search_path='' as $$begin if not private.has_permission('field_app') then raise exception 'Permission denied'; end if; return private.set_field_status_atomic_impl(p_job_id,p_requested_status,p_no_materials); end$$;

revoke all on function public.add_field_material_atomic(uuid,text,text,numeric,numeric),public.add_job_note_atomic(uuid,text,text),public.add_work_time_atomic(uuid,numeric),public.approve_fleet_assignment_atomic(uuid,uuid,timestamptz,timestamptz,numeric,numeric,numeric,numeric,text,timestamptz,timestamptz),public.assign_technician_atomic(uuid,uuid),public.cancel_job_atomic(uuid,text),public.consume_inventory_for_job(uuid,uuid,numeric),public.create_job_atomic(uuid,text,text,timestamptz,timestamptz),public.finalize_job_photo_atomic(uuid,text,text),public.reschedule_job_atomic(uuid,timestamptz,timestamptz),public.set_field_status_atomic(uuid,text,boolean) from public,anon;
grant execute on function public.add_field_material_atomic(uuid,text,text,numeric,numeric),public.add_job_note_atomic(uuid,text,text),public.add_work_time_atomic(uuid,numeric),public.approve_fleet_assignment_atomic(uuid,uuid,timestamptz,timestamptz,numeric,numeric,numeric,numeric,text,timestamptz,timestamptz),public.assign_technician_atomic(uuid,uuid),public.cancel_job_atomic(uuid,text),public.consume_inventory_for_job(uuid,uuid,numeric),public.create_job_atomic(uuid,text,text,timestamptz,timestamptz),public.finalize_job_photo_atomic(uuid,text,text),public.reschedule_job_atomic(uuid,timestamptz,timestamptz),public.set_field_status_atomic(uuid,text,boolean) to authenticated;
