-- Move owner/permission and pricing SECURITY DEFINER operations out of the exposed public schema.
-- Public RPC contracts remain unchanged and run as SECURITY INVOKER.

alter function public.set_role_permission_atomic(text,text,boolean) set schema private;
alter function public.set_user_permission_override_atomic(uuid,text,text) set schema private;
alter function public.update_company_pricing_settings_atomic(numeric,numeric,numeric,numeric,boolean) set schema private;
alter function public.create_price_book_item_atomic(text,text,text,text,numeric,numeric,numeric,numeric) set schema private;
alter function public.create_price_book_learning_proposal_atomic(uuid,uuid,text,integer,numeric,numeric,numeric,numeric,text) set schema private;
alter function public.save_price_book_tier_atomic(uuid,text,text,text,numeric,numeric,numeric,numeric) set schema private;
alter function public.update_price_book_item_atomic(uuid,numeric,numeric,numeric,numeric) set schema private;

grant usage on schema private to authenticated;
grant execute on function private.set_role_permission_atomic(text,text,boolean),private.set_user_permission_override_atomic(uuid,text,text),private.update_company_pricing_settings_atomic(numeric,numeric,numeric,numeric,boolean),private.create_price_book_item_atomic(text,text,text,text,numeric,numeric,numeric,numeric),private.create_price_book_learning_proposal_atomic(uuid,uuid,text,integer,numeric,numeric,numeric,numeric,text),private.save_price_book_tier_atomic(uuid,text,text,text,numeric,numeric,numeric,numeric),private.update_price_book_item_atomic(uuid,numeric,numeric,numeric,numeric) to authenticated;

create function public.set_role_permission_atomic(p_role text,p_permission_key text,p_allowed boolean) returns void language plpgsql security invoker set search_path='' as $$begin perform private.set_role_permission_atomic(p_role,p_permission_key,p_allowed); end$$;
create function public.set_user_permission_override_atomic(p_user_id uuid,p_permission_key text,p_mode text) returns void language plpgsql security invoker set search_path='' as $$begin perform private.set_user_permission_override_atomic(p_user_id,p_permission_key,p_mode); end$$;
create function public.update_company_pricing_settings_atomic(p_labor_rate numeric,p_minimum_gp numeric,p_default_overhead numeric,p_membership_discount numeric,p_allow_owner_below_floor boolean) returns boolean language sql security invoker set search_path='' as $$select private.update_company_pricing_settings_atomic($1,$2,$3,$4,$5)$$;
create function public.create_price_book_item_atomic(p_code text,p_category text,p_name text,p_description text,p_material_cost numeric,p_labor_hours numeric,p_overhead numeric,p_target_gp numeric) returns uuid language sql security invoker set search_path='' as $$select private.create_price_book_item_atomic($1,$2,$3,$4,$5,$6,$7,$8)$$;
create function public.create_price_book_learning_proposal_atomic(p_item_id uuid,p_tier_id uuid,p_service_type text,p_sample_size integer,p_current_hours numeric,p_proposed_hours numeric,p_current_gp numeric,p_proposed_gp numeric,p_evidence text) returns uuid language sql security invoker set search_path='' as $$select private.create_price_book_learning_proposal_atomic($1,$2,$3,$4,$5,$6,$7,$8,$9)$$;
create function public.save_price_book_tier_atomic(p_item_id uuid,p_tier text,p_name text,p_description text,p_material_cost numeric,p_labor_hours numeric,p_overhead numeric,p_target_gp numeric) returns uuid language sql security invoker set search_path='' as $$select private.save_price_book_tier_atomic($1,$2,$3,$4,$5,$6,$7,$8)$$;
create function public.update_price_book_item_atomic(p_id uuid,p_material_cost numeric,p_labor_hours numeric,p_overhead numeric,p_target_gp numeric) returns uuid language sql security invoker set search_path='' as $$select private.update_price_book_item_atomic($1,$2,$3,$4,$5)$$;

revoke all on function public.set_role_permission_atomic(text,text,boolean),public.set_user_permission_override_atomic(uuid,text,text),public.update_company_pricing_settings_atomic(numeric,numeric,numeric,numeric,boolean),public.create_price_book_item_atomic(text,text,text,text,numeric,numeric,numeric,numeric),public.create_price_book_learning_proposal_atomic(uuid,uuid,text,integer,numeric,numeric,numeric,numeric,text),public.save_price_book_tier_atomic(uuid,text,text,text,numeric,numeric,numeric,numeric),public.update_price_book_item_atomic(uuid,numeric,numeric,numeric,numeric) from public,anon;
grant execute on function public.set_role_permission_atomic(text,text,boolean),public.set_user_permission_override_atomic(uuid,text,text),public.update_company_pricing_settings_atomic(numeric,numeric,numeric,numeric,boolean),public.create_price_book_item_atomic(text,text,text,text,numeric,numeric,numeric,numeric),public.create_price_book_learning_proposal_atomic(uuid,uuid,text,integer,numeric,numeric,numeric,numeric,text),public.save_price_book_tier_atomic(uuid,text,text,text,numeric,numeric,numeric,numeric),public.update_price_book_item_atomic(uuid,numeric,numeric,numeric,numeric) to authenticated;
