drop policy if exists "dispatch manage route recommendations" on public.dispatch_route_recommendations;
create policy "dispatch insert route recommendations" on public.dispatch_route_recommendations for insert to authenticated with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'csr_dispatch'::text])) and private.has_permission('manage_dispatch'::text));
create policy "dispatch update route recommendations" on public.dispatch_route_recommendations for update to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'csr_dispatch'::text])) and private.has_permission('manage_dispatch'::text)) with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'csr_dispatch'::text])) and private.has_permission('manage_dispatch'::text));
create policy "dispatch delete route recommendations" on public.dispatch_route_recommendations for delete to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'csr_dispatch'::text])) and private.has_permission('manage_dispatch'::text));

drop policy if exists "managers manage inventory locations" on public.inventory_locations;
create policy "managers insert inventory locations" on public.inventory_locations for insert to authenticated with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text])) and private.has_permission('manage_inventory'::text));
create policy "managers update inventory locations" on public.inventory_locations for update to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text])) and private.has_permission('manage_inventory'::text)) with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text])) and private.has_permission('manage_inventory'::text));
create policy "managers delete inventory locations" on public.inventory_locations for delete to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text])) and private.has_permission('manage_inventory'::text));

drop policy if exists "purchasing manage purchase order items" on public.purchase_order_items;
create policy "purchasing insert purchase order items" on public.purchase_order_items for insert to authenticated with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and private.has_permission('manage_purchasing'::text));
create policy "purchasing update purchase order items" on public.purchase_order_items for update to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and private.has_permission('manage_purchasing'::text)) with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and private.has_permission('manage_purchasing'::text));
create policy "purchasing delete purchase order items" on public.purchase_order_items for delete to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and private.has_permission('manage_purchasing'::text));

drop policy if exists "purchasing manage purchase orders" on public.purchase_orders;
create policy "purchasing insert purchase orders" on public.purchase_orders for insert to authenticated with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and private.has_permission('manage_purchasing'::text));
create policy "purchasing update purchase orders" on public.purchase_orders for update to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and private.has_permission('manage_purchasing'::text)) with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and private.has_permission('manage_purchasing'::text));
create policy "purchasing delete purchase orders" on public.purchase_orders for delete to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and private.has_permission('manage_purchasing'::text));

drop policy if exists "purchasing manage suppliers" on public.suppliers;
create policy "purchasing insert suppliers" on public.suppliers for insert to authenticated with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text])) and private.has_permission('manage_purchasing'::text));
create policy "purchasing update suppliers" on public.suppliers for update to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text])) and private.has_permission('manage_purchasing'::text)) with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text])) and private.has_permission('manage_purchasing'::text));
create policy "purchasing delete suppliers" on public.suppliers for delete to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text])) and private.has_permission('manage_purchasing'::text));

drop policy if exists "authorized manage vendor bill drafts" on public.vendor_bill_drafts;
create policy "authorized insert vendor bill drafts" on public.vendor_bill_drafts for insert to authenticated with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and (private.has_permission('manage_purchasing'::text) or private.has_permission('manage_accounting'::text)));
create policy "authorized update vendor bill drafts" on public.vendor_bill_drafts for update to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and (private.has_permission('manage_purchasing'::text) or private.has_permission('manage_accounting'::text))) with check ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and (private.has_permission('manage_purchasing'::text) or private.has_permission('manage_accounting'::text)));
create policy "authorized delete vendor bill drafts" on public.vendor_bill_drafts for delete to authenticated using ((private.current_employee_role() = any (array['owner'::text,'manager'::text,'accounting'::text])) and (private.has_permission('manage_purchasing'::text) or private.has_permission('manage_accounting'::text)));
