import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { requireCurrentUser } from '@/lib/session';
import { serviceTitanGet } from '@/lib/servicetitan';

export const dynamic = 'force-dynamic';
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const when=(v?:string|null)=>v?new Date(v).toLocaleDateString('en-US',{timeZone:'America/New_York',year:'numeric',month:'short',day:'numeric'}):'—';
const since=(v?:string|null)=>{if(!v)return 'Unknown';const d=new Date(v),n=new Date(),months=Math.max(0,(n.getFullYear()-d.getFullYear())*12+n.getMonth()-d.getMonth());if(months<1)return 'Less than 1 month';if(months<12)return `${months} month${months===1?'':'s'}`;const y=Math.floor(months/12),m=months%12;return `${y} year${y===1?'':'s'}${m?` ${m} mo`:''}`};
function contactValues(row:any){const values:any[]=[];if(!row||typeof row!=='object')return values;for(const item of [row,...(Array.isArray(row.contacts)?row.contacts:[])]){const type=String(item?.type??item?.contactType??'').toLowerCase();const value=item?.value??item?.phoneNumber??item?.email??null;if(value)values.push({type:type||'contact',value:String(value),memo:item?.memo||item?.name||item?.title||null});}return values;}

export default async function ServiceTitanCustomerPage({params}:{params:Promise<{id:string}>}){
  await requireCurrentUser();
  const {id}=await params;
  const supabase=await createSupabaseServerClient();
  const {data,error}=await supabase.rpc('get_service_titan_customer_history',{p_customer_id:id});
  if(error||!data||(data as any).customer==null) notFound();
  const h:any=data,c=h.customer||{},a=c.address||{},jobs:any[]=h.jobs||[],appointments:any[]=h.appointments||[],invoices:any[]=h.invoices||[],locations:any[]=h.locations||[];
  let contacts:any[]=[];
  try{const response:any=await serviceTitanGet(`/crm/v2/tenant/{tenant}/contacts/relationships/${encodeURIComponent(id)}?page=1&pageSize=50&includeTotal=true`);contacts=(Array.isArray(response?.data)?response.data:[]).flatMap(contactValues);}catch{}
  const dates=[c.createdOn,...jobs.map(j=>j.createdOn||j.completedOn)].filter(Boolean).map(v=>new Date(v).getTime()).filter(Number.isFinite);const customerSince=dates.length?new Date(Math.min(...dates)).toISOString():c.createdOn||null;
  const completedJobs=jobs.filter(j=>String(j.jobStatus||'').toLowerCase()==='completed');
  const lastService=[...jobs].filter(j=>j.completedOn||j.createdOn).sort((x,y)=>new Date(y.completedOn||y.createdOn).getTime()-new Date(x.completedOn||x.createdOn).getTime())[0];
  const lifetimeRevenue=Number(h.lifetimeRevenue||0),avgTicket=completedJobs.length?lifetimeRevenue/completedJobs.length:jobs.length?lifetimeRevenue/jobs.length:0;
  const primaryPhone=contacts.find(x=>x.type.includes('phone'))?.value,primaryEmail=contacts.find(x=>x.type.includes('email'))?.value;
  const address=[a.street,a.unit,a.city,a.state,a.zip].filter(Boolean).join(', ');
  return <main style={{fontFamily:'system-ui',maxWidth:1250,margin:'auto',padding:28}}>
    <p><Link href="/customers">← Customer CRM</Link></p>
    <header style={{border:'1px solid #d8d8d8',borderRadius:18,padding:22,marginBottom:18,boxShadow:'0 1px 3px rgba(0,0,0,.05)'}}><div style={{display:'flex',justifyContent:'space-between',gap:18,flexWrap:'wrap',alignItems:'start'}}><div style={{maxWidth:720}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><small style={{fontWeight:800,textTransform:'uppercase',letterSpacing:'.08em',color:'#666'}}>Customer profile</small><span style={{border:'1px solid #bbb',borderRadius:999,padding:'3px 8px',fontSize:11,fontWeight:800}}>SERVICETITAN · READ ONLY</span></div><h1 style={{fontSize:35,margin:'5px 0 8px'}}>{c.name||`ServiceTitan Customer ${id}`}</h1><div style={{display:'grid',gap:5,fontSize:15}}><div><b>{c.type||'Customer'}</b> · {c.active===false?'Inactive':'Active'} · ST #{id}</div><div><b>Phone:</b> {primaryPhone||'No phone returned by contact feed'}</div><div><b>Email:</b> {primaryEmail||'No email returned by contact feed'}</div><div><b>Billing address:</b> {address||'No address loaded'}</div></div></div><div style={{minWidth:245,borderLeft:'4px solid #111',paddingLeft:14}}><small>Lifetime customer value</small><div style={{fontSize:36,fontWeight:900}}>{money.format(lifetimeRevenue)}</div><div style={{fontSize:14,color:'#555'}}>Customer for {since(customerSince)}</div><div style={{fontSize:13,color:'#666'}}>Since {when(customerSince)}</div></div></div></header>

    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(155px,1fr))',gap:10,margin:'18px 0'}}>{[['Lifetime Revenue',money.format(lifetimeRevenue)],['Lifetime Jobs',jobs.length],['Completed Jobs',completedJobs.length],['Average Job Value',money.format(avgTicket)],['Open A/R',money.format(Number(h.openBalance||0))],['Last Service',when(lastService?.completedOn||lastService?.createdOn)],['Locations',locations.length]].map(([k,v])=><div key={String(k)} style={{border:'1px solid #ddd',borderRadius:14,padding:14}}><small>{k}</small><div style={{fontWeight:850,fontSize:21,marginTop:3}}>{v}</div></div>)}</section>

    <section style={{border:'1px solid #ddd',borderRadius:16,padding:17,margin:'18px 0'}}><h2 style={{marginTop:0}}>Contact & Account Information</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12}}><div><small>Customer since</small><div><b>{when(customerSince)}</b> · {since(customerSince)}</div></div><div><small>Account status</small><div><b>{c.active===false?'Inactive':'Active'}</b>{c.doNotService?' · DO NOT SERVICE':''}</div></div><div><small>Account balance</small><div><b>{money.format(Number(c.balance??h.openBalance??0))}</b></div></div><div><small>Mail preference</small><div><b>{c.doNotMail?'Do not mail':'Mail allowed'}</b></div></div></div>{contacts.length>0&&<div style={{marginTop:16,borderTop:'1px solid #eee',paddingTop:12}}><b>Contact methods</b><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:8,marginTop:8}}>{contacts.map((x:any,i:number)=><div key={`${x.type}-${x.value}-${i}`} style={{border:'1px solid #eee',borderRadius:10,padding:10}}><small style={{textTransform:'capitalize'}}>{x.type}</small><div style={{fontWeight:750}}>{x.value}</div>{x.memo&&<small>{x.memo}</small>}</div>)}</div></div>}</section>

    <section style={{border:'1px solid #ddd',borderRadius:16,padding:17,margin:'18px 0'}}><h2 style={{marginTop:0}}>Properties / Service Locations</h2>{locations.length?<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:10}}>{locations.map((l:any)=>{const la=l.address||{};return <div key={l.id} style={{border:'1px solid #eee',borderRadius:12,padding:12}}><b>{l.name||'Service location'}</b><div>{[la.street,la.unit,la.city,la.state,la.zip].filter(Boolean).join(', ')||'Address not loaded'}</div><small>Location #{l.id}</small></div>})}</div>:<p>No service locations found.</p>}</section>

    <h2>Service History</h2>{jobs.slice(0,100).map((j:any)=><article key={j.id} style={{border:'1px solid #ddd',borderRadius:14,padding:16,margin:'10px 0'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><h3 style={{margin:'0 0 6px'}}>Job {j.jobNumber||j.id}</h3><div><b>{money.format(Number(j.total||0))}</b> · {j.jobStatus||'Unknown'}</div></div><p>{j.summary||j.summaryOfWork||'No summary loaded.'}</p><details><summary style={{cursor:'pointer',fontWeight:700}}>More job details</summary><p><b>Created:</b> {when(j.createdOn)} • <b>Completed:</b> {when(j.completedOn)} • <b>Business unit:</b> {j.businessUnitId||'—'} • <b>Invoice:</b> {j.invoiceId||'—'}</p></details></article>)}{!jobs.length&&<p>No ServiceTitan jobs found.</p>}

    <h2 style={{marginTop:30}}>Financial History</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Invoice','Date','Total','Balance','Paid'].map(x=><th key={x} style={{textAlign:'left',padding:10,borderBottom:'1px solid #ccc'}}>{x}</th>)}</tr></thead><tbody>{invoices.slice(0,100).map((i:any)=><tr key={i.id}><td style={{padding:10,borderBottom:'1px solid #eee'}}>{i.referenceNumber||i.id}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{when(i.invoiceDate)}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{money.format(Number(i.total||0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{money.format(Number(i.balance||0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{when(i.paidOn)}</td></tr>)}</tbody></table></div>
  </main>;
}
