import { createSupabaseServerClient } from '@/lib/supabase/server';
import { requireCurrentUser } from '@/lib/session';

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const number=new Intl.NumberFormat('en-US',{maximumFractionDigits:0});
const pretty=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
export const dynamic='force-dynamic';

export default async function MarketingSetupPage(){
  await requireCurrentUser();const supabase=await createSupabaseServerClient();
  const [{data:qa},{data:queue},{data:dashboard},{data:diag},{data:leads},{data:unknownCalls},{data:providers}]=await Promise.all([
    supabase.rpc('marketing_attribution_qa',{p_days:30}),supabase.rpc('marketing_sync_queue_summary'),supabase.rpc('marketing_attribution_dashboard',{p_days:30}),supabase.rpc('marketing_attribution_diagnostics',{p_days:30}),supabase.rpc('marketing_lead_queue',{p_days:30,p_limit:200}),supabase.rpc('marketing_unmatched_call_queue',{p_days:30,p_limit:200}),supabase.rpc('marketing_provider_connection_summary'),
  ]);
  const q:any=qa??{},d:any=dashboard??{},h:any=diag??{},rows:any[]=(queue as any[])??[],leadRows:any[]=(leads as any[])??[],callRows:any[]=(unknownCalls as any[])??[],providerRows:any[]=(providers as any[])??[];
  const origins=(process.env.MARKETING_TRACKING_ALLOWED_ORIGINS||'').split(',').map(v=>v.trim()).filter(Boolean);const scriptSrc='https://durfee-performance-ai.vercel.app/api/marketing/client';const snippet=`<script src="${scriptSrc}" defer></script>`;const formSnippet='<form data-durfee-lead="service-request">…</form>';const phoneSnippet='<a href="tel:+15085551212" data-durfee-phone>(508) 555-1212</a>';
  return <main style={{fontFamily:'system-ui',maxWidth:1180,margin:'auto',padding:32}}>
    <header><p style={{fontWeight:800,letterSpacing:1}}>MARKETING TRACKING</p><h1>Tracking & Attribution Health</h1><p>Pre-authorization control room for website clicks/forms, dynamic phone numbers, Dialpad linkage, revenue reconciliation and future Google/Meta uploads.</p></header>
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,margin:'24px 0'}}>{[
      ['Website origins',origins.length],['Tracking numbers',h.trackingNumbers??0],['Website leads',leadRows.length],['New/unmatched leads',leadRows.filter(x=>x.status==='new').length],['Unknown inbound calls',callRows.filter(x=>x.match_status==='unmatched').length],['Unlinked paid sessions',q.unlinkedIdentifiedTouchpoints??0],['Jobs without attribution',q.jobsWithoutAttribution??0],['Failed provider syncs',q.failedSyncs??0]
    ].map(([label,value])=><article key={String(label)} style={{border:'1px solid #ddd',borderRadius:14,padding:16}}><small>{label}</small><h2 style={{marginBottom:0}}>{number.format(Number(value??0))}</h2></article>)}</section>

    <section style={{border:'1px solid #ddd',borderRadius:16,padding:20,margin:'24px 0'}}><h2 style={{marginTop:0}}>Website tracker</h2><p>The tracker keeps one first-party session, captures Google/Meta click IDs, UTMs and campaign/ad hierarchy, swaps marked phone elements, and adds <code>durfee_marketing_session</code> to forms. Only forms explicitly marked <code>data-durfee-lead</code> are copied into the Durfee lead inbox.</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',background:'#f6f7f8',padding:14,borderRadius:10}}><code>{snippet}</code></pre><p><b>Track a lead form:</b></p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',background:'#f6f7f8',padding:14,borderRadius:10}}><code>{formSnippet}</code></pre><p><b>Dynamic phone element:</b></p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',background:'#f6f7f8',padding:14,borderRadius:10}}><code>{phoneSnippet}</code></pre><p><b>Allowed origins:</b> {origins.length?origins.join(', '):'Not configured yet'}</p><p><small>The browser tracker sends attribution data only to Durfee Performance. Google/Meta uploads remain server-side and disabled until authorization.</small></p></section>

    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,margin:'24px 0'}}>
      <article style={{border:'1px solid #ddd',borderRadius:16,padding:18}}><h2 style={{marginTop:0}}>Revenue truth</h2><p><b>Earned/completed:</b> {money.format(Number(d.earnedRevenue??0))}</p><p><b>Collected:</b> {money.format(Number(d.collectedRevenue??0))}</p><p><b>ROAS basis:</b> {Number(d.collectedRevenue??0)>0?'Collected payments':'Completed-job revenue until payment data exists'}</p></article>
      <article style={{border:'1px solid #ddd',borderRadius:16,padding:18}}><h2 style={{marginTop:0}}>Attribution chain</h2><p>Click/session → website form or tracking number → Dialpad call → customer → job → completion → invoice → payment.</p><p>Unknown callers are now retained in a separate marketing-call queue instead of being discarded just because a CRM customer does not exist yet.</p></article>
      <article style={{border:'1px solid #ddd',borderRadius:16,padding:18}}><h2 style={{marginTop:0}}>Ad connections</h2>{providerRows.map((p:any)=><p key={p.provider}><b>{p.provider==='google_ads'?'Google Ads':'Meta Ads'}:</b> {pretty(p.connection_status)}</p>)}<p>Queues cannot be claimed by signed-in users and remain inactive until server-side authorization succeeds.</p></article>
    </section>

    <section style={{marginTop:30}}><h2>Provider conversion queue</h2>{rows.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Provider','Status','Events','Value','Oldest Event'].map(x=><th key={x} style={{textAlign:'left',padding:10,borderBottom:'1px solid #ccc'}}>{x}</th>)}</tr></thead><tbody>{rows.map((r:any)=><tr key={`${r.provider}:${r.status}`}><td style={{padding:10,borderBottom:'1px solid #eee'}}>{r.provider==='google_ads'?'Google Ads':'Meta Ads'}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{pretty(r.status)}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{number.format(Number(r.event_count??0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{money.format(Number(r.total_value??0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{r.oldest_event?new Date(r.oldest_event).toLocaleString():'—'}</td></tr>)}</tbody></table></div>:<p>No provider conversion events are queued yet.</p>}</section>

    <section style={{marginTop:30}}><h2>Go-live checklist</h2><ol><li>Allow the real public website origin in <code>MARKETING_TRACKING_ALLOWED_ORIGINS</code>.</li><li>Install the tracker script.</li><li>Mark only genuine service/contact forms with <code>data-durfee-lead</code>.</li><li>Mark displayed phone elements with <code>data-durfee-phone</code>.</li><li>Provision a Dialpad tracking-number pool and route it to the normal Durfee call destination.</li><li>Test a paid-style URL and confirm the click/session, form lead and dynamic number appear here.</li><li>Confirm an unknown caller is retained and a known caller links through to customer/job.</li><li>Authorize Google Ads and validate the current offline/enhanced-lead path before recurring uploads.</li><li>Authorize Meta Ads and validate test conversion events before recurring uploads.</li></ol></section>
  </main>;
}
