'use server';
import { revalidatePath } from 'next/cache';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { assertPermission } from '@/lib/permissions';

function finiteNonnegative(v:FormDataEntryValue|null){const n=Number(v??0);if(!Number.isFinite(n)||n<0)throw new Error('Invalid inventory values');return n;}
function optionalNonnegative(v:FormDataEntryValue|null){const raw=String(v??'').trim();if(!raw)return null;const n=Number(raw);if(!Number.isFinite(n)||n<0)throw new Error('Invalid inventory values');return n;}
function optionalUuid(v:FormDataEntryValue|null){const value=String(v??'').trim();return value||null;}
function clean(v:FormDataEntryValue|null){return String(v??'').trim();}
async function authorize(){await assertPermission('manage_inventory');}
async function rpc(name:string,args:Record<string,unknown>){const supabase=await createSupabaseServerClient();const {error}=await supabase.rpc(name,args);if(error)throw new Error(error.message||'Inventory operation failed');revalidatePath('/inventory');}

export async function createInventoryItem(formData:FormData){await authorize();const sku=clean(formData.get('sku')),description=clean(formData.get('description')),location=clean(formData.get('location')),onHand=finiteNonnegative(formData.get('on_hand')),reorder=finiteNonnegative(formData.get('reorder_point')),cost=finiteNonnegative(formData.get('unit_cost'));if(!sku||!description||!location)throw new Error('Invalid inventory item');await rpc('create_inventory_item_atomic',{p_sku:sku,p_description:description,p_location:location,p_on_hand:onHand,p_reorder_point:reorder,p_unit_cost:cost});}
export async function updateInventoryItem(formData:FormData){await authorize();const id=clean(formData.get('id')),onHand=finiteNonnegative(formData.get('on_hand')),reorder=finiteNonnegative(formData.get('reorder_point')),cost=finiteNonnegative(formData.get('unit_cost')),expectedOnHand=finiteNonnegative(formData.get('expected_on_hand')),expectedReorder=finiteNonnegative(formData.get('expected_reorder_point')),expectedCost=finiteNonnegative(formData.get('expected_unit_cost'));if(!id)throw new Error('Invalid inventory values');await rpc('update_inventory_item_atomic',{p_id:id,p_expected_on_hand:expectedOnHand,p_expected_reorder_point:expectedReorder,p_expected_unit_cost:expectedCost,p_on_hand:onHand,p_reorder_point:reorder,p_unit_cost:cost});}
export async function createInventoryLocation(formData:FormData){await authorize();const name=clean(formData.get('name')),type=clean(formData.get('location_type'));if(!name)throw new Error('Location name required');await rpc('create_inventory_location',{p_name:name,p_location_type:type,p_assigned_user_id:optionalUuid(formData.get('assigned_user_id'))});}
export async function configureInventoryItem(formData:FormData){await authorize();const id=clean(formData.get('inventory_item_id'));if(!id)throw new Error('Inventory item required');await rpc('update_inventory_item_operations',{p_inventory_item_id:id,p_location_id:optionalUuid(formData.get('location_id')),p_barcode:clean(formData.get('barcode'))||null,p_bin_code:clean(formData.get('bin_code'))||null,p_max_stock:optionalNonnegative(formData.get('max_stock')),p_supplier_id:optionalUuid(formData.get('supplier_id')),p_supplier_sku:clean(formData.get('supplier_sku'))||null});}
export async function recordCycleCount(formData:FormData){await authorize();const itemId=clean(formData.get('inventory_item_id')),locationId=clean(formData.get('location_id')),counted=finiteNonnegative(formData.get('counted_quantity'));if(!itemId||!locationId)throw new Error('Item and location required');await rpc('record_inventory_cycle_count',{p_inventory_item_id:itemId,p_location_id:locationId,p_counted_quantity:counted,p_photo_url:clean(formData.get('photo_url'))||null,p_note:clean(formData.get('note'))||null});}
export async function transferInventoryStock(formData:FormData){await authorize();const itemId=clean(formData.get('inventory_item_id')),from=clean(formData.get('from_location_id')),to=clean(formData.get('to_location_id')),quantity=finiteNonnegative(formData.get('quantity'));if(!itemId||!from||!to||quantity<=0)throw new Error('Valid stock transfer required');await rpc('transfer_inventory_stock',{p_inventory_item_id:itemId,p_from_location_id:from,p_to_location_id:to,p_quantity:quantity});}
export async function recordSupplierCost(formData:FormData){await authorize();const itemId=clean(formData.get('inventory_item_id')),unitCost=finiteNonnegative(formData.get('unit_cost')),source=clean(formData.get('source'))||'manual';if(!itemId)throw new Error('Inventory item required');await rpc('record_supplier_cost_observation',{p_inventory_item_id:itemId,p_supplier_id:optionalUuid(formData.get('supplier_id')),p_supplier_sku:clean(formData.get('supplier_sku'))||null,p_unit_cost:unitCost,p_source:source,p_observed_at:new Date().toISOString()});}
