import { createSupabaseServerClient } from '@/lib/supabase/server';
import { requireCurrentUser } from '@/lib/session';
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
export default async function JobsPage(){
  await requireCurrentUser();const supabase=await createSupabaseServerClient();
  const {data,error}=await supabase.from('jobs').select('id,status,revenue,material_cost,labor_cost,allocated_overhead,scheduled_start,customers(name,service_address),users(name)').order('created_at',{ascending:false}).limit(100);
  const jobs=error?[]:(data??[]);
  return <main style={{fontFamily:'system-ui',maxWidth:1250,margin:'auto',padding:32}}><h1>Jobs & Workflow</h1><p>Live booking, scheduling, dispatch, field-work and profitability records.</p>{error&&<p role="alert">Jobs could not be loaded.</p>}<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',marginTop:24}}><thead><tr>{['Job','Customer','Technician','Scheduled','Status','Revenue','GP'].map(x=><th key={x} style={{textAlign:'left',padding:12,borderBottom:'1px solid #ccc'}}>{x}</th>)}</tr></thead><tbody>{jobs.map((j:any)=>{const r=Number(j.revenue??0);const c=Number(j.material_cost??0)+Number(j.labor_cost??0)+Number(j.allocated_overhead??0);const gp=r>0?((r-c)/r)*100:null;return <tr key={j.id}><td style={{padding:12,borderBottom:'1px solid #eee'}}>{j.id.slice(0,8)}</td><td style={{padding:12,borderBottom:'1px solid #eee'}}>{j.customers?.name||'—'}</td><td style={{padding:12,borderBottom:'1px solid #eee'}}>{j.users?.name||'Unassigned'}</td><td style={{padding:12,borderBottom:'1px solid #eee'}}>{j.scheduled_start?new Date(j.scheduled_start).toLocaleString():'—'}</td><td style={{padding:12,borderBottom:'1px solid #eee'}}>{j.status}</td><td style={{padding:12,borderBottom:'1px solid #eee'}}>{money.format(r)}</td><td style={{padding:12,borderBottom:'1px solid #eee'}}>{gp===null?'—':`${gp.toFixed(1)}%`}</td></tr>})}</tbody></table>{!jobs.length&&!error&&<p style={{marginTop:24}}>No jobs have been created yet.</p>}</div></main>;
}
