import { createSupabaseServerClient } from '@/lib/supabase/server';
import { requireCurrentUser } from '@/lib/session';

export const dynamic='force-dynamic';
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const number=new Intl.NumberFormat('en-US',{maximumFractionDigits:0});
const platform=(s:string)=>s==='google_ads'?'Google Ads':s==='meta_ads'?'Facebook / Instagram':s||'Unknown';

export default async function MarketingCampaignsPage(){
 await requireCurrentUser();const supabase=await createSupabaseServerClient();const {data,error}=await supabase.rpc('marketing_campaign_revenue_performance',{p_days:30,p_limit:200});const rows:any[]=(data as any[])??[];
 return <main style={{fontFamily:'system-ui',maxWidth:1380,margin:'auto',padding:32}}><header><p style={{fontWeight:800,letterSpacing:1}}>CAMPAIGN REVENUE</p><h1>Paid Media → Durfee Revenue</h1><p>Platform spend and clicks are compared with first-party sessions, calls, booked jobs, completed jobs and Durfee revenue. Collected payments drive ROAS when available; completed-job revenue is the fallback.</p></header>{error&&<p role="alert">Campaign revenue report could not be loaded.</p>}<div style={{overflowX:'auto',marginTop:24}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Platform','Campaign','Spend','Clicks','Sessions','Calls','Booked','Completed','Earned','Collected','ROAS'].map(x=><th key={x} style={{textAlign:'left',padding:10,borderBottom:'1px solid #ccc'}}>{x}</th>)}</tr></thead><tbody>{rows.map((r:any)=><tr key={`${r.platform}:${r.campaign_key}`}><td style={{padding:10,borderBottom:'1px solid #eee'}}>{platform(r.platform)}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}><b>{r.campaign_name||r.campaign_key||'(not set)'}</b><br/><small>{r.campaign_key&&r.campaign_key!==r.campaign_name?r.campaign_key:''}</small></td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{money.format(Number(r.spend||0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{number.format(Number(r.clicks||0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{number.format(Number(r.sessions||0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{number.format(Number(r.calls||0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{number.format(Number(r.booked_jobs||0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{number.format(Number(r.completed_jobs||0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{money.format(Number(r.earned_revenue||0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{money.format(Number(r.collected_revenue||0))}</td><td style={{padding:10,borderBottom:'1px solid #eee'}}>{r.roas==null?'—':`${Number(r.roas).toFixed(2)}×`}</td></tr>)}</tbody></table>{!rows.length&&!error&&<p>No native paid-media metrics and matched campaign sessions are available yet. ServiceTitan historical campaign activity remains visible on the command center until the ad accounts are authorized.</p>}</div></main>;
}
